### ISSUE TITLE
BuildTools version

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#115]
It looks like there are no recent tags/releases of this package which is used by source-build. BuildToolsVersion.txt is referring to a myget package.

**Comment by omajid** [comment]
The usual approach of `strings <path-to-so-dll-or-exe> | grep @` on a BuildTools dll doesnt get me a commit id either.

**Comment by crummel** [comment]
Hi guys, I think this might have been fixed with our recent build and BuildTools updates - I downloaded [version 2.0.0-servicing-02104-04](https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.DotNet.BuildTools/2.0.0-servicing-02104-04) from [BuildToolsVersion.txt](https://github.com/dotnet/source-build/blob/b7527b5e6c1a4fcd515d7c774c3a0122655286dc/BuildToolsVersion.txt) and checked the file properties for the hash, which gave me https://github.com/dotnet/buildtools/commit/21e36983f28a5e587e300c506641f1b698b6decb.  I'll close this for now, please reopen or let me know if you're still seeing this issue.

**Comment by omajid** [comment]
Stupid question. How does one do that on Linux? It seems `exiftool` can do it for some, but not all `.dll` files I throw at it.

**Comment by crummel** [comment]
Interesting, that particular file doesn't show properties on Windows either.
Bad file: `./x64/Release/smoke/sdk/15.5.1-preview-006908/Newtonsoft.Json.dll: PE32+ executable (DLL) (console) Unknown processor type 0xfd1d Mono/.Net assembly, for MS Windows`
Good file: `./x64/Release/smoke/sdk/15.5.1-preview-006908/Sdks/Microsoft.NET.Sdk.Publish/tools/net46/Newtonsoft.Json.dll: PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows`

I'm looking into this.

**Comment by tmds** [comment]
I think the difference is, one is a managed assembly the other is ngened.

**Comment by crummel** [comment]
That makes sense, that won't apply to BuildTools then as all of that code is managed.
