### ISSUE TITLE
Prebuilt Removal: Investigate runtime.native.System.Data.SqlClient.sni in corefx

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1267]
The following indirect prebuilts are being included in corefx.  These need to be investigated to see how they can be eliminated:

Name | Version
:-- | --
runtime.win-arm64.runtime.native.System.Data.SqlClient.sni | 4.4.0
runtime.win-arm64.runtime.native.System.Data.SqlClient.sni | 4.4.0
runtime.win-x64.runtime.native.System.Data.SqlClient.sni | 4.4.0
runtime.win-x64.runtime.native.System.Data.SqlClient.sni | 4.4.0
runtime.win-x86.runtime.native.System.Data.SqlClient.sni | 4.4.0
runtime.win-x86.runtime.native.System.Data.SqlClient.sni | 4.4.0

**Comment by dseefeld** [comment]
@ericstj Any suggestions on these packages that are being identified as indirect prebuilts in source-build?

**Comment by ericstj** [comment]
These are required for running SqlClient on *windows*.  IIRC this component is still built from an internal repo owned by the SqlClient team, so you won't be able to *eliminate* it unless you change the product architecture or open-source that component, both of which I believe are non-goals.  /cc @cheenamalhotra, @Gary-Zh , @david-engel

I suspect you'll only ever restore these when attempting to run tests on Windows, which I don't expect is a goal of source-build.  Can you just condition this out of source-build, then disable those tests?

**Comment by cheenamalhotra** [comment]
Yes they are referenced by **System.Data.SqlClient** and **Microsoft.Data.SqlClient**, before that I have a question.

We have an issue from customer https://github.com/dotnet/SqlClient/issues/236 and have recently seen that these "runtime" libraries are now available in "C:\Program Files\dotnet\sdk\NuGetFallbackFolder", is that what this is about? As it didn't happen before. We are dependent on this library, but I'm not sure if this was expected to be shipped with dotnet build.

Please elaborate the purpose behind the NuGetFallbackFolder, so we can make better decision.

**Comment by ericstj** [comment]
Fallback folders: https://github.com/NuGet/Home/wiki/%5BSpec%5D-Fallback-package-folders
The SDK installs packages here to avoid hitting nuget servers in order to install packages.  It's commonly done for packages which need to be available for project template creation.  It's an end-user feature, not an aspect of our build-infrastructure for the product.

This issue has nothing to do with that feature.  This issue is about building the corefx repo without ever needing to restore bre-built packages.  Since this component by-definition is not part of the product composition it will always be a pre-built.  I believe we need to provide advice to @dseefeld to avoid downloading the packages.

I think we want to condition the following to not happen for source build:
https://github.com/dotnet/corefx/blob/c22714d65151968a17c3b232748880d5e7961dee/src/System.Data.SqlClient/tests/FunctionalTests/System.Data.SqlClient.Tests.csproj#L40
https://github.com/dotnet/corefx/blob/777dbdec193fcbe49b3f18614348ac96f77d57c3/eng/restore/runtime/runtime.depproj#L29

**Comment by dseefeld** [comment]
Thanks @ericstj.  I'll try to condition those out.
