### ISSUE TITLE
Patches fail to apply on Fedora 25

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#132]
Some patches fail to apply due to different line endings:
```
  patch -p1 --ignore-whitespace -i /home/tmds/repos/source-build/patches/nuget-client/0001-Revert-38949ce93081016167dfd8e37e4e897bedf47d65-DOS-.patch
  (Stripping trailing CRs from patch; use --binary to disable.)
  patching file build/common.project.props
  Hunk #1 FAILED at 14 (different line endings).
  1 out of 1 hunk FAILED -- saving rejects to file build/common.project.props.rej
  (Stripping trailing CRs from patch; use --binary to disable.)
  patching file src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj
  Hunk #1 FAILED at 5 (different line endings).
  Hunk #2 FAILED at 51 (different line endings).
  2 out of 2 hunks FAILED -- saving rejects to file src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj.rej
```
This is not failing in CI since it is using a different patch command

https://github.com/dotnet/source-build/blob/14d33dc2af2be062d842ff93c8410e34b6b89a93/targets/repository.proj#L45-L46

CI should use the same command as non-CI builds.
Can we use the `git apply` command always (since that is working)? Or should we use `patch` also in CI?

CC @crummel @omajid

**Comment by omajid** [comment]
As I understand it, in our build-for-distribution scenario, we are building from a source tarball and dont have a clone of the git repo. Since `git` is not generally needed, a previous maintainer thought it was better to not have a build dependency on git at all. He added the support for `patch`.

If `patch` vs `git` is causing issues, I think we should just take a build-time dependency on `git` (for `git apply`) and stop worrying about differences in how they apply patches. We have too many other things to worry about already :)

**Comment by tmds** [comment]
Fixed by https://github.com/dotnet/source-build/pull/135
