### ISSUE TITLE
Investigate issues with internal authenticated feeds

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1491]
NuGet feeds that require authentication do not work on internal builds even though we have the correct secrets injected into the build, leading to patches like [this one](https://github.com/dotnet/source-build/blob/7ce7c99f6dba507a7a063ca5c982197c3c42a58a/patches/aspnet-extensions/0006-Patch-out-authed-feeds.patch).  We should do this properly instead of patching feeds out and checking in binaries.

**Comment by dagood** [comment]
It looks like even with auth working, we still also need a way to remove these feeds dynamically so that once the commit goes public, it's able to be built. (The plan of record I remember is that the internal bits get pushed to one of the open feeds also in the nuget.config, so that we're able to do this.) I'd suggest creating a target to do these removals rather than using patches.

**Comment by MichaelSimons** [comment]
[Triage]  This has been addressed by the [`Setup Private Feeds Credentials` step](https://github.com/dotnet/installer/blob/main/src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml#L55) in CI.
