### ISSUE TITLE
Make Mono source-build-clean

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1513]
Mono as currently built in runtime is not source-build-clean and restores prebuilt assets during the build.  We will need to fix this and upstream any patches required.  This should only affect the System.Private.CoreLib build; the libcoreclr build should not be bringing in prebuilts.

**Comment by omajid** [comment]
We are using mono (the VM, the alternative to CoreCLR) from the .NET runtime repo on s390x as a part of source-build. I am not aware of anything special that needs to be done; everything works fine out of the box right now.

I think the last set of issues was fixed by https://github.com/dotnet/runtime/pull/61607?

IMO we should close this issue now.

**Comment by omajid** [comment]
Closing this issue based on my previous comment.

@crummel, please feel free to re-open this issue if I missed something.
