### ISSUE TITLE
source-build 5.0 includes an asset cache file

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1656]
After building source-build 5.0 preview 4, I see an unexpected file:

```
dotnet/packs/NETStandard.Library.Ref/2.1.0/netstandard.library.ref/2.1.0/Debug/netstandard2.0/netstandard.library.ref.assets.cache
```

It seems to be the only one, though:

```
$ find /usr/lib64/dotnet/ -iname '*.cache' 
/usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/netstandard.library.ref/2.1.0/Debug/netstandard2.0/netstandard.library.ref.assets.cache
$ find /usr/lib64/dotnet/ -iname 'Debug'
/usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/netstandard.library.ref/2.1.0/Debug
$ find /usr/lib64/dotnet/ -iname 'Release'
```

**Comment by dagood** [comment]
This is a known issue with SBRP including some build-time assets, I believe because of the way it packs the nuspec: https://github.com/dotnet/source-build/issues/1620. We closed it in triage because it hasn't caused any failures, and it's already fixed in the 5.0 SBRP work. (But that won't necessarily apply to 3.1...)

Probably would be a similar fix as https://github.com/dotnet/source-build-reference-packages/pull/121 if it's worth fixing in 3.1.

**Comment by dagood** [comment]
I missed that this issue is about 5.0... it does seem to be there in 3.1 as well for me though. This issue gets a little bit hairy because this would have started showing up when this line was introduced to switch 3.1 over to use SBRP for targeting packs, in 3.1.104:

https://github.com/dotnet/source-build/blob/a0438857c6dcd46ee5524a5484118655a4bb1060/repos/core-setup.common.props#L24-L25

**Comment by dseefeld** [comment]
@dseefeld to fix before the next servicing release.

**Comment by omajid** [comment]
Can we close this issue now? Is there anything else that needs to be fixed?

**Comment by dseefeld** [comment]
> Can we close this issue now? Is there anything else that needs to be fixed?

The attached PR hasn't been merged, yet.  I'm waiting for the latest update to SBRP with the casing fixes.  The CI build failed, so I'm re-running it to get the latest "official" build updated.
