### ISSUE TITLE
Building bootstrap cli fails for 5.0 previews

### ISSUE THREAD

**Issue by jsclary** [dotnet/source-build#1680]
scripts/bootstrap/buildbootstrapcli.sh fails with "No such file" error duing the "DETECTING GIT COMMIT HASHES" phase while trying to get the strings from the System.Native.so. That library isn't present in 5.0 Preview 6 or 7 though a libSystem.Native.so is. As the script doesn't appear to have been touched in 11 months, I assume it just hasn't been updated to support the changes in 5.0, yet. It seems to continue fine when adding the lib prefix. I'll update if I run into further issues.

**Comment by dagood** [comment]
Yeah, it makes sense that this unfortunately isn't up to date.

If you're able to get it working, a PR would be welcome. 🙂 /cc @janvorli @omajid 

(This makes me wonder where this script will go in 5.0, since we're moving the source-build concept out of the dotnet/source-build repo itself. Filed https://github.com/dotnet/source-build/issues/1681 for that question.)

**Comment by jsclary** [comment]
Thanks, that related issue does seem fairly important. I'm having to work on a 3.1 build for now due to time constraints. Fixing the shared library name just revealed further issues with changed/moved/merged repos that'll likely require multiple changes. I'll try to come back to the 5.0 issue in a few days.

**Comment by MichaelSimons** [comment]
[Triage] This issue is obsolete. 5.0 is now EOL.
