### ISSUE TITLE
Q: blazor support

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#1721]
How does blazor support fit into the sdk, and what does it mean for source-build?
Is it something ships out-of-band for source-build SDKs? And for Microsoft SDKs?

@dagood @crummel @dseefeld @omajid @RheaAyase @aslicerh

**Comment by dagood** [comment]
We had a source-build meeting about this a bit ago, @directhex looked into some of the details and I'll try to recap:

When you do `dotnet new blazorwasm`, it downloads `Microsoft.NETCore.App.Runtime.browser-wasm`, a runtime pack produced from dotnet/runtime. This means we can't include it in a source-built SDK currently:

* We don't have a way to ship any source-built runtime packs yet. https://github.com/dotnet/source-build/issues/1215
* `browser-wasm` is handed as an extra platform in dotnet/runtime, so we need to either build dotnet/runtime multiple times, or get a single build command that can build multiple platforms.
  * Doesn't seem like an impossible problem so much as something we need to figure out.
* It's difficult to build `browser-wasm`. The build depends on emscripten, which doesn't exist in many distros, and where it does, it seems to be a very old version. So, anyone trying to build .NET from source would have problems beyond .NET infra, unless we took on emscripten maintenance.

However, since runtime packs are downloaded from nuget.org automatically, I would expect the feature to still work when using a source-built SDK. It'll just have to use a Microsoft-built runtime pack.

One thing to watch out for is any SDK functionality that might be missing in the source-built SDK that's necessary to apply the runtime pack properly. It seems worthwhile to add a `blazorwasm` app to our smoke tests to make sure.

/cc @dleeapho

**Comment by tmds** [comment]
> This means we can't include it in a source-built SDK

Does Microsoft ship this with the SDK?

> Microsoft.NETCore.App.Runtime.browser-wasm, a runtime pack produced from dotnet/runtime.

Is this the mono-based runtime that eventually runs inside the browser?

> It seems worthwhile to add a blazorwasm app to our smoke tests to make sure.

+1 definitly!

**Comment by dagood** [comment]
> Does Microsoft ship this with the SDK?

No, the Microsoft-built SDK can also only acquire runtime packs from nuget.org.

> Is this the mono-based runtime that eventually runs inside the browser?

My understanding is it's the Mono runtime compiled via emscripten to run in the browser, plus libraries. This is something I'm less familiar with though.

**Comment by dseefeld** [comment]
It looks like the questions have been answered here.  Blazor will be added to 5.0 smoke-tests (#1724).

**Comment by tmds** [comment]
@dagood, thank you for clarifying how Blazor fits into the source-build SDK.
