### ISSUE TITLE
Remove patches from websdk

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#179]
Remove all from https://github.com/dotnet/source-build/tree/dev/release/2.0/patches/websdk

**Comment by natemcmaster** [comment]
Adding @vijayrkn and @mlorbetske  for https://github.com/aspnet/websdk

**Comment by natemcmaster** [comment]
I'm not sure which branch source-build points since it's not mentioned here: https://github.com/dotnet/source-build/blob/73d81eefe104f6584a6028281a045dc511726949/.gitmodules#L31-L33, but to close this out, I'm assuming this work would need to be backported, right? Then we can update this submodule in this repo and get rid of the patch files in this repo.
