### ISSUE TITLE
When will you have 3.1.200 released?

### ISSUE THREAD

**Issue by linqing2004** [dotnet/source-build#1842]
The latest 3.1.109 don't support "dotnet nuget add ...". I wonder when will you have source build for 3.1.200?

**Comment by dagood** [comment]
We won't ever build 3.1.200 because it's not a secure version, and more generally, the whole 3.1.2xx feature band of SDK versions is EOL, so we won't build e.g. 3.1.202 either.

I think you really want 3.1.4xx? (An SDK feature band that's in support and `>=` 3.1.2xx?)

Context: the latest released 3.1 SDK versions are 3.1.109 and 3.1.403--all 3.1.2xx and 3.1.3xx SDKs are missing security patches: https://dotnet.microsoft.com/download/dotnet-core/3.1.

Source-build supports the oldest in-service feature band (currently 3.1.1xx) for compatibility reasons: we don't want to break our users any more than necessary. 3.1.4xx, like any new feature band, has some breaking changes. Band-to-band breaks are expected to be minor, but that's a matter of opinion and case-by-case impact.

We could support source-build for multiple SDK feature bands at the same time. The problem is that it takes a significant chunk of ongoing time to maintain source-build for multiple 3.1 SDK feature bands, so we don't have a plan to do that for 3.1. (In future major releases, we aim to reduce the maintenance cost to make this feasible: https://github.com/dotnet/source-build/issues/1743.)

---

All that said, an upgrade to a new band may happen sometime down the line. Once 3.1.1xx goes EOL, we'll have switch to some other SDK feature band still in support to maintain our overall 3.1 support.

I think a generally accurate way to get the EOL date is following these VS version pointers from the download page like this one:

> ![image](https://user-images.githubusercontent.com/12819531/97454681-05eed080-1905-11eb-991d-bf2b39a10984.png)

through a search engine to these support pages:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.4
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes (v16.7 as of writing)

the 16.7 one says:

> In addition, now that version 16.7 is available, version 16.4, which was the last servicing baseline, will be supported for an additional 12 months and will go out of support in October 2021.

I think at that point the 3.1.1xx band will go EOL because VS no longer needs it, and we'll need to move to 3.1.4xx.

**Comment by dseefeld** [comment]
@linqing2004 We think this question is answered.  If you have any other questions or comments, please let us know.
