### ISSUE TITLE
vstest.console is missing debug symbols

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1874]
I tried building an SDK from the current master branch and running it through [check-debug-symbols](https://src.fedoraproject.org/rpms/dotnet3.1/blob/master/f/check-debug-symbols.py):

```
error: missing .debug_info section in  dotnet/sdk/5.0.100/vstest.console
error: missing .debug_abbrev section dotnet/sdk/5.0.100/vstest.console
error: missing FILE symbols in dotnet/sdk/5.0.100/vstest.console
```

Some other info:

```
$ file dotnet/sdk/5.0.100/vstest.console
dotnet/sdk/5.0.100/vstest.console: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=23473f4299002b6bf3aad7044f3ad355bd25191d, not stripped
$ readelf --section-headers dotnet/sdk/5.0.100/vstest.console | grep -E 'debug|gnu'
  [ 3] .note.gnu.build-i NOTE             00000000000002ac  000002ac
  [ 4] .gnu.hash         GNU_HASH         00000000000002d0  000002d0
  [ 7] .gnu.version      VERSYM           00000000000020b8  000020b8
  [ 8] .gnu.version_r    VERNEED          0000000000002210  00002210
  [29] .gnu_debuglink    PROGBITS         0000000000000000  000214f7

```

It's `not stripped` (?) and has a `.gnu_debuglink` section (which is supposed to point to a file that has the debug information) but doesn't actually contain debug information sections (`.debug_info` and `.debug_abbrev`).

What created this file? Perhaps it was pre-processed by the build system? I am going to dig further into this as soon as I find some time.

**Comment by omajid** [comment]
cc @tmds

**Comment by dagood** [comment]
This looks like an apphost... first because of the files near it that seem like the "rest" of the app:

```
vstest.console
vstest.console.deps.json
vstest.console.dll
vstest.console.dll.config
vstest.console.runtimeconfig.json
```

and then it does have the string `apphost` in it (but not sure why this string is there, other than it being the original name of the template binary file):

```
#> strings sdk/sdk/5.0.100/vstest.console | grep apphost
  - %s&apphost_version=%s
apphost
apphost.dbg
```

The Microsoft SDK doesn't have a `vstest.console` host... I think we ended up with one because of this patch:

https://github.com/dotnet/source-build/blob/8d3666b97b0ec8e228e7c578cdac1d210fadb994/patches/vstest/0006-build-for-.NET-5.patch#L200-L206

In 3.0 we started generating an apphost by default, so I think the TFM change triggers that. I believe we can add `<UseAppHost>false</UseAppHost>` to that patch to get rid of it. https://github.com/dotnet/core/issues/3686

The apphost template binary most likely comes from the tooling/prebuilt SDK (`.dotnet/packs/Microsoft.NETCore.App.Host.linux-x64`), so I think we need to get rid of it for clean source-build.

(If we actually need to create an apphost in some other situation, I think we *should* be able to force a project to use the apphost pack we build in dotnet/runtime rather than the one in the tooling SDK. I don't know offhand how to do that though, and it isn't the right direction in this case anyway.)

**Comment by dagood** [comment]
Done in https://github.com/dotnet/source-build/pull/1875, thanks @tmds!

(The "fixes #..." link doesn't fire because `release/3.1` is still our default branch rather than `master`. 😄)
