### ISSUE TITLE
5.0 RTM isn't tagged

### ISSUE THREAD

**Issue by azixaka** [dotnet/source-build#1913]

**Comment by azixaka** [comment]
@tmds @RheaAyase

**Comment by omajid** [comment]
Duplicate of https://github.com/dotnet/source-build/issues/1891?

**Comment by dagood** [comment]
Yeah, we don't have `v5.0.100-SDK`/`v5.0.0-runtime` tags because we don't have it done yet. (If you install ZenHub, you should be able to see remaining issues in https://github.com/dotnet/source-build/issues/1891.)

There's also an end-user-facing issue tracking this here: [**.NET 5 is missing in RHEL (CentOS) & Fedora** dotnet/core#5596](https://github.com/dotnet/core/issues/5596)

Closing as duplicate.
