### ISSUE TITLE
Tell me what the error is about?

### ISSUE THREAD

**Issue by blackcross86** [dotnet/source-build#1923]
![2020-11-25_16-53](https://user-images.githubusercontent.com/74768319/100236660-0350bc80-2f3f-11eb-80e4-5408ed07e0ee.png)

**Comment by omajid** [comment]
Let me take a shot.

.NET really, really likes to download prebuilt binaries during build. That's not an ideal state for open source software, which should be buildable using only sources. Some Linux distributions (such as Fedora and Debian) even enforce that. To accomodate them, source-build has set up a system where the build fails if any prebuilt downloads are found after building .NET. However, for 5.0, that's not fully done yet: the build still (as of right now) downloads some prebuilts during the build process. (We want to fix this for 5.0 GA). Since some prebuilts are downloaded at used at build time, the build system finds that out and fails the build.

You can disable this by passing an argument to the build script. It would look something like `./build.sh -- /p:ContinueOnPrebuiltBaselineError=true` or `./build-source-tarball.sh --skip-prebuilt-check`

**Comment by blackcross86** [comment]
> Позвольте мне сделать снимок.
> 
> .NET очень любит загружать готовые двоичные файлы во время сборки. Это не идеальное состояние для программного обеспечения с открытым исходным кодом, которое должно быть построено с использованием только исходных кодов. Некоторые дистрибутивы Linux (такие как Fedora и Debian) даже применяют это. Для их размещения в source-build настроена система, в которой сборка завершается ошибкой, если после сборки .NET обнаруживаются какие-либо предварительно созданные загрузки. Однако для 5.0 это еще не сделано: сборка все еще (на данный момент) загружает некоторые предварительные сборки в процессе сборки. (Мы хотим исправить это в версии 5.0 GA). Поскольку некоторые предварительные сборки загружаются при использовании во время сборки, система сборки обнаруживает это и завершает сборку неудачно.
> 
> Вы можете отключить это, передав аргумент сценарию сборки. Это будет выглядеть примерно так `./build.sh -- /p:ContinueOnPrebuiltBaselineError=true`или`./build-source-tarball.sh --skip-prebuilt-check`

Thanks for it, here's another problem.
![2020-11-26_15-07](https://user-images.githubusercontent.com/74768319/100349183-1cb63f00-2ff9-11eb-870e-4f711610702b.png)

**Comment by blackcross86** [comment]
> Let me take a shot.
> 
> .NET really, really likes to download prebuilt binaries during build. That's not an ideal state for open source software, which should be buildable using only sources. Some Linux distributions (such as Fedora and Debian) even enforce that. To accomodate them, source-build has set up a system where the build fails if any prebuilt downloads are found after building .NET. However, for 5.0, that's not fully done yet: the build still (as of right now) downloads some prebuilts during the build process. (We want to fix this for 5.0 GA). Since some prebuilts are downloaded at used at build time, the build system finds that out and fails the build.
> 
> You can disable this by passing an argument to the build script. It would look something like `./build.sh -- /p:ContinueOnPrebuiltBaselineError=true` or `./build-source-tarball.sh --skip-prebuilt-check`

Thanks for it, here's another problem.
![2020-11-26_15-07](https://user-images.githubusercontent.com/74768319/100349278-43747580-2ff9-11eb-9b01-c3a64e80f3c8.png)
