### ISSUE TITLE
Full source bootstrap

### ISSUE THREAD

**Issue by cireu** [dotnet/source-build#1930]
source-build project help a lot on building dotnet from source and simplify the packaging step on most distro.
But it still requires a binary seed as stage0, some distro(like Guix) has stricter rule, it requires a full source bootstrap.

So the question is: Is it possible to do a full source bootstrap? If there's a minimal dotnet compiler and runtime written in another language(e.g. C++ or Haskell) which enable us to build and run an old version of dotnet framework. Then we can use this dotnet sdk to bootstrap any newer version.

**Comment by dagood** [comment]
Unfortunately not. 😕 There are several tools in the .NET SDK that are self-hosting with very tight cycles, taking dependencies on essentially daily builds. For example, Roslyn takes dependencies on new C# features very quickly, so you can't build the 5.0.100 Roslyn using the 3.1.110 Roslyn. (5.0.100 is essentially the next version after 3.1.110 right now.) The sequence of commits you'd have to build to get from one to the the other might be prohibitively long, and AFAIK nobody is tracking this. Fortunately we avoid using floating versions in our repos, so it should be trace*able*. But I don't think we have tooling to do that tracing.

Building a .NET SDK using C++ would let you start at 5.0.100, and we *do* support building 5.0.100 -> 5.0.101 -> 5.0.102 using source-build. But setting up a bootstrap .NET SDK would be a lot of work. There's much more than the runtime libraries and Roslyn: a lot of build tooling is self-hosting, like MSBuild, NuGet, Arcade, etc. Also, this bootstrap .NET SDK would probably need to be individually maintained for every version (5.0, 6.0, 7.0, ...) because there's no nice pathway from one to the next.

Out of curiosity I looked at how Rust (self-hosting compiler) got in Guix, and [yeah, there's a Rust built in C++ that was the initial version](https://guix.gnu.org/blog/2018/bootstrapping-rust/). That's pretty neat. 😄 I see that [now there are ~28 versions in the chain](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/rust.scm). This is longer than I expected, so I guess length isn't necessarily a big problem. (Note that all of those versions appear to be stable versions, though, unlike a .NET SDK chain would be.)

For the current distros that use source-build and disallow prebuilts, they all have a bootstrap exception for self-hosting compilers that .NET fits into. (Sounds like you're aware, but mentioning for broader context. 🙂)

It would be great to be able to include .NET in stricter distros. Full source bootstrap does also help us get into other distros too--skip the prebuilt bootstrap exception. But it seems like it will be very difficult.

**Comment by Kreijstal** [comment]
oh this would be nice, we could port dotnet to cygwin

**Comment by Kreijstal** [comment]
@dagood someone adding a patch https://issues.guix.gnu.org/74609 this might be of interest to you
