### ISSUE TITLE
[ArPow] Onboard command-line-api to arcade-powered source-build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2038]

**Comment by omajid** [comment]
PR: https://github.com/dotnet/command-line-api/pull/1204

**Comment by omajid** [comment]
PR was merged upstream.

Can someone please help verify the artifacts? Or can someone please teach me how I can do that myself?

**Comment by MichaelSimons** [comment]
@omajid because we should be inspecting the internal builds, you will unfortunately not be able to self-service.

I took a look at the build and say that it was waiting for some additional permissions.  I permitted and the build completed.  I verified the intermediate package was created with the same packages the 5.0 sb build produces.  I also took a look at the prebuilts and am signing off.
