### ISSUE TITLE
[ArPow Tarball] Move Arcade specific infrastructure to Arcade

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2295]
While developing the tarball creation process in the installer repo, some infrastructure that should belong in Arcade is being included in installer to aid in iterative development.  When the tarball process is complete, this code should move to Arcade.

**Comment by premun** [comment]
@MichaelSimons I am curious about this one, the timeline and how much do you really plan to do this one?

Currently, I am planning to move some logic around, namely creation of `git-info/` files would be part of the VMR tooling so I'd move the logic into **DarcLib** (which is now consumed in `installer`). This improves some things as for isntance in DarcLib, there is already code for reading `Version.Details.xml` files but in a more organized [strong-typed manner](https://github.com/dotnet/arcade-services/blob/f169af20efd542ef8aba38154efb9ccd22eba2c4/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs#L1393-L1402) than in installer's SB implementation. I would probably extend the functionality there to understand the SB tags and build on top of that.

My question is then whether we can move this into `arcade-services` rather than `arcade` (asking about the tarball MSBuild tasks too)? Will the tarball tasks be used in other places so `arcade` would be better then?

**Comment by crummel** [comment]
I think it would make sense for some of this to move into arcade-services rather than arcade.  It's probably call-by-call whether something should go into one or the other - we can discuss particular instances in the ProdCon or weekly sync I think.

**Comment by MichaelSimons** [comment]
This issue is superseded by https://github.com/dotnet/source-build/issues/3138.  This Arcade specific infrastructure has now been replaced with the VMR infrastructure.
