### ISSUE TITLE
CLI is always reinstalled by init-tools.sh

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#239]
This is making the CLI always install on my Fedora 26 runs (and probably other shells):

https://github.com/dotnet/source-build/blob/51f2c9ae3aabf8168df046fa0474be3dd2997822/init-tools.sh#L17-L20

> /home/dagood/git/here-source-build/init-tools.sh: line 19: return: can only `return' from a function or sourced script

Two fixes come to mind:
 1. Wrap the rest of the file with `else` rather than trying to early return.
 2. Put the code in a function and keep using `return`.

@weshaggard @eerhardt

**Comment by weshaggard** [comment]
Most repo's are sourcing in the init-tools script which is why we needed it to be a return instead of exit. That said I was under the impression that return should turn into an exit if it is an outer script, perhaps my understand is incorrect on that front.

I will do some testing but if this is blocking you the easiest fix is to source in the script from build.sh.

**Comment by dagood** [comment]
Looking at the PR that changed from executing to sourcing (https://github.com/dotnet/corefx/pull/19363), switching to sourcing is actually better anyway. The only remaining problem is anyone calling `./init-tools.sh`, but I don't have a reason to support that.
