### ISSUE TITLE
We should re-think where nuget symbol packages go

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#252]
From https://github.com/dotnet/source-build/blob/dev/release/2.0/Documentation/auto-dependency-flow/api.md#recommended-implementation-4

> Place NuGet library packages (*.nupkg) directly in $(DotNetOutputBlobFeedDir)packages/.
> Place all other assets, such as installers, lzma files, and NuGet symbol packages (*.symbols.nupkg), in $(DotNetOutputBlobFeedDir)assets/.

This doesn't play well with `dotnet pack`.  `dotnet pack` has an `--output` parameter, but as far as I can tell, there is no way to specify that you want the non-symbols package to go to one folder, and the symbols package to go to a different folder.  `dotnet pack` will place them both in a single folder.

See https://github.com/NuGet/NuGet.Client/blob/63e8539791d4f662efffceb2185ad4510396d76e/src/NuGet.Core/NuGet.Build.Tasks.Pack/GetPackOutputItemsTask.cs#L54-L62

If this is our policy, then every repo that uses `dotnet pack` will have to manually copy files around, which is less than ideal.

@dotnet/source-build-contrib

**Comment by dagood** [comment]
The reason it's spec'd this way right now is because that's how transport/blob feeds are spec'd. Sorry for the Msft link: [Package-Acquisition.md#layout](https://github.com/dotnet/core-eng/blob/0d8c4d14f323db79efea820171b11923e8ed52c9/Documentation/Project-Docs/Package-Acquisition.md#layout). @chcosta @karajas @jcagme @markwilkie is this open to change or flexibility?

I agree that it makes the most sense to lay blob feeds out in the way that is most easily compatible with the product features we ship.

Background: a scenario where splitting them up helps a lot is when you only have access to rudimentary tools and need to treat lib packages vs. symbol packages differently. E.g. push to different feeds, push all libs and no symbols, etc., when all you can do is run `nuget` commands with basic globbing. The difficulty is that `*.nupkg` also matches `*.symbols.nupkg`. Just mentioning this to get it out of the way: **we aren't limited in this way for source-build/product-build**, and isolated builds can continue to split them up if it helps them.

**Comment by MichaelSimons** [comment]
[Triage] Closing - This api is dead and therefore this issue is no longer relevant.
