### ISSUE TITLE
Investigate cause of increased online build times

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2561]
Recently the online build times in CI have increased by ~1/2 hr.  The offline builds are not affected.

![image](https://user-images.githubusercontent.com/8290530/138519665-c85b8f9a-70c4-4354-aed6-daa1bb6578ed.png)

Diff of the changes between the two builds where this was first noticed - https://github.com/dotnet/installer/compare/a2c7b5b27746526eab5d4512a29ff446ec633114...7ae99ce59f8729427e9e0b307b99c8fd20ddf2fd

The orchestration binlog should be helpful in diagnosing as you can easily retrieve the individual repo build times.

**Comment by MichaelSimons** [comment]
Investigating a recent CI build (https://dev.azure.com/dnceng/internal/_build/results?buildId=1443335&view=results) I found the following:

1. In this particular build the online build took ~43m longer than the offline build. Each repo build appears to be on the order of 2m longer.  There are 26 repos which accounts for the total time difference.
2. Inspecting a few repos give hints that this extra time is coming someplace withing the common build.sh script.  The tarball's build binlog gives the time to build each repo.  For example source-link RepoBuild is 15.335s offline vs 2:26.036s online.  Looking at the binlogs for the sourcelink repo shows 14.794s for the offline build vs 14.323s for the online build.  This seems to imply the extra 2 minutes is coming someplace within the build.sh before the actual build is invoked.

**Comment by MattGal** [comment]
@MichaelSimons you may be right; there's a decent chance it was the change I made to log Client IPs when in -ci build mode, so I filed https://github.com/dotnet/arcade/issues/8205 and will remove it today.  

I'm not fully convinced this is it because the repo logs we get have no timestamp and both offline and online log "`Attempting to log this clients IP for Azure Package feed telemetry purposes`".  The time wasted is pretty accurate though for curl-ing a dead URL. In the case of the version of Arcade in the runtime repo today, the URL is wrong, so unless being offline makes curl return instantly it should be close to the same amount of time to try to curl an non-existent endpoint.  Azure doesn't promise the new, still-working URL will keep working and it was only useful the one time, so I will kill it anyways.

Something else to try if you can easily rig up the experiment would be to set low / delete the values for the NUGET_CLIENT_EXPERIMENTAL_RETRY work I did.  (see https://github.com/dotnet/arcade/blob/main/eng/common/tools.sh#L421-L433).  Amusingly this is the work that fell out of the IP logging above.  It causes there to be much more retry when it can actually get to Nuget endpoints, so when I merge the change to remove the logging for the above issue if the problem doesn't get instantly better this is your next thing to check out.  This one's harder to change because without it, online builds tend to fail at ~1% rate in restore which for a runtime run makes a lot of total failures.

**Comment by MattGal** [comment]
@MichaelSimons after you up-take the arcade changes for https://github.com/dotnet/arcade/issues/8205  (or via patch)  if you don't see improvement let's talk about the NuGet.Client stuff.

**Comment by MichaelSimons** [comment]
Thanks @MattGal.  I will keep an eye out for the changes to flow into each repo.

To provide clarity on why I thought the Client IP logging was the source.  The source-build test change (e.g. hack) I ran to disable the IP logging was this - https://github.com/dotnet/installer/commit/8a059b22f23e13910317d670bb9497a05532f5ca.  Because this is common eng infra, it's a fair amount of work to patch in source-build because you have to touch each repo.  This change dynamically edits the common tools script to replace the offline check to think it is always building offline.  This is why you still saw the `Attempting to log this clients IP for Azure Package feed telemetry purposes` message in the output.

**Comment by MattGal** [comment]
Ooooh, ok in that case I have much higher confidence that this will fix the delta between on- and off-line.  I'll do the 6.0 port now.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/8212 ports the same change to 6.0.

**Comment by MichaelSimons** [comment]
This was resolved with https://github.com/dotnet/arcade/issues/8205.  The telemetry logging was removed.  It will still need to flow into the product repos.
