### ISSUE TITLE
.net debugger looks for .NET source code when justMyCode is false

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#2623]
Our .NET builds include pdbs. This causes the debugger in vscode to go look for the .NET source code when justMyCode is set to false.

I see this issue on Fedora 34 with the rc2 build. And also on RHEL 8 with the final build.

**Steps to reproduce**

Create a new web app:
```
dotnet new web -o web
cd web
dotnet build
code .
```
Add a launch configuration for .NET in VS Code.
Edit the config and add `"justMyCode": false`.
Start the debugger.
When the app has started, pause the app in the debugger.

Error messages like this show up:
![error](https://user-images.githubusercontent.com/1025424/142016975-6b8df17c-8410-4296-b9e3-0dcc48fe0281.png)

When removing the pdbs from the .NET installation, the error messages are no longer shown.

cc @omajid @dseefeld

**Comment by tmds** [comment]
> What does the debugger get from the pdb files? In other words: what is lost when we don't include the pdb files?

According to https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2022, the pdb files are used to map source code to the assemblies. So if we are not making available source code in a way that is consumable for the end-user, we should not include the pdb files either.

@dsplaisted is this correct?

What `DebugType` does source-build use when generating pdbs?
How does this work for the Microsoft build? Are pdbs generated? Of what `DebugType`? Where are they uploaded?

**Comment by omajid** [comment]
If we were to make the source code available too, what would that look like?

I ask because some other language runtimes produce a "src.zip" as part of their output. The (equivalent of) pdb files plus that src.zip gives end-users the full ability to walk and step through all the code in their favourite debugger. Is that something .NET (source-build in particular) could do?

**Comment by tmds** [comment]
> If we were to make the source code available too, what would that look like?

I think the 'modern' way is to use [sourcelink](https://github.com/dotnet/sourcelink). I don't know if it requires pdbs as an intermediate, or whether the assemblies reference the source repository directly.

[The doc](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2022) talks about source servers that are referenced from the pdb. It's not clear if this is relates to sourcelink, or whether it is a different mechanism.

**Comment by dsplaisted** [comment]
@clairernovotny @tmat Any guidance here on how debugging into .NET code should work with source-built .NET?

**Comment by clairernovotny** [comment]
PDB's contain the source link information, which pulls in the linked source code. In general, we publish our PDB's to a symbol server, so they're not shipped alongside the framework but they are available on-demand. Then VS/Code can load the symbols on demand if you want to debug into that module. 

That seems to be the sweet spot for the framework itself, so that developers aren't source debugging the full framework by default but they can step in when desired.

**Comment by tmds** [comment]
@clairernovotny for Microsoft builds, you publish the pdbs to a server.
Is VS/Code preconfigured to use this server?

After it got the pdbs from the server, it finds the sources directly on github.com based on the sourcelink information that is in the pdbs? Is that correct?

For source-build, we should investigate if we can make the sources available so they can be used by the debugger.

Until we do that: do the pdbs still contain something useful for the debugger in the absence of source code?
If they don't, we can just remove them from our build.
If they do. Can we change the pdb that gets built (by source-build) so it provides the useful information and no longer causes the debugger to try find the unavailable sources?

**Comment by clairernovotny** [comment]
Looping in @tmat to help answer some of these.

**Comment by tmat** [comment]
@gregg-miskelly Does presence of PDB next to the DLL indicate "my code" to the debugger?

**Comment by gregg-miskelly** [comment]
> Does presence of PDB next to the DLL indicate "my code" to the debugger?
To be clear, this question started out asking about behavior with `"justMyCode": false`, in which case "my code" doesn't apply.
But for folks who do have just my code enabled (the default) -- code is considered my code if BOTH: the module has just-in-time compiler optimizations disabled, and a PDB can be found.

To reply to some of the other things asked/said in this issue:

PDBs contain more than just mapping between source code<->IL methods/offsets. For example, the names of all the local variables. But generally if you don't have source code that info is of very limited value.

Source Link data embeds additional information into the PDB. So, if Source Link is enabled, but the PDBs are placed anywhere that the debugger can find them (like on a symbol server, or next to the dll) then it isn't useful.

> Is VS/Code preconfigured to use this server?
Not by default, though there are builtin options to enable it. For VS Code, see: https://github.com/OmniSharp/omnisharp-vscode/wiki/Debugging-into-the-.NET-Framework-itself for more info.

> After it got the pdbs from the server, it finds the sources directly on github.com based on the sourcelink information that is in the pdbs? Is that correct?
Correct

> Until we do that: do the pdbs still contain something useful for the debugger in the absence of source code?
If you have enabled Source Link: yes, otherwise, no

**Comment by tmds** [comment]
> If you have enabled Source Link: yes, otherwise, no

Based on this, I think we should we exclude the pdbs.

Longer term, we should see in what way source-build users can expose their source-code, and how source-build can be pointed to that location.

@omajid does that make sense?

Do we want source-build to exclude the pdbs, or it it something we want to handle as part of the packaging?

**Comment by tmds** [comment]
We fixed this by excluding the pdbs.
