### ISSUE TITLE
Add CI legs for Docker images

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#273]
Currently we have Docker images in the repo: https://github.com/dotnet/source-build/tree/c761530289f45d79dc38f517b017c90911fa9f7a/docker, but we do not verify in CI that we can build on any of them.  @dseefeld ran into an issue with the images so it seems like we should be building on these and updating them as necessary, or remove them entirely.

**Comment by dleeapho** [comment]
I think we need to reconcile the Dockerfiles in this repo with those we publish to https://hub.docker.com/r/microsoft/dotnet-buildtools-prereqs/ This work is tracked in https://github.com/dotnet/core-eng/issues/533 part of that work is to make the source Dockerfiles public. Once that is done we should remove the Dockerfiles in this repo.
/cc @MichaelSimons @ravimeda

**Comment by dagood** [comment]
As part of this (I think?) we should start building Fedora 28 using Docker instead of the `Fedora.28.Amd64.Open` queue. The machines on the queue only have 26 GB free when fresh, and buildup seems to cause our CI to fail after a while. (Caused problems in https://github.com/dotnet/source-build/pull/746.)

**Comment by dseefeld** [comment]
Fixed with #749 and #755
