### ISSUE TITLE
Couldn't run dotnet in arch linux. 

### ISSUE THREAD

**Issue by nishu-murmu** [dotnet/source-build#2772]
I installed dotnet and it's sdk from pacman
Tried to run it but instead it is showing me this below error.
```
dotnet: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by dotnet)
```

**Comment by MichaelSimons** [comment]
[Triage] @nishu-murmu - can you please provide the exact package name that you installed?

**Comment by nishu-murmu** [comment]
> [Triage] @nishu-murmu - can you please provide the exact package name that you installed?

```
sudo pacman -S dotnet-ask dotnet-runtime
```

**Comment by omajid** [comment]
Thanks for getting back to us. Did you mean `dotnet-sdk` instead of `dotnet-ask`?

[`dotnet-runtime`](https://archlinux.org/packages/community/x86_64/dotnet-runtime/) is a source-build package, so this does feel like an issue that was introduced while building .NET. The Arch Linux package maintainer, @alucryd, might have a better idea about what's going on.

My only guess is that the glibc version you have installed is too old and you need to update, along the lines of `pacman -Syu`?

**Comment by alucryd** [comment]
Apologies for the delay, I'm a bit underwater. @nishu-murmu I can't reproduce here, if your system is up to date you should have glibc 2.35, can you run a full update as @omajid suggested with `pacman -Syu`?
