### ISSUE TITLE
Add Fedora Rawhide to source-build CI

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#2992]
Adding Fedora Rawhide to our CI would help us catch source-build and product issues even earlier than just running the latest version of Fedora.

**Comment by lbussell** [comment]
Related:

- https://github.com/dotnet/installer/pull/14321
- https://github.com/dotnet/source-build/issues/2813

**Comment by omajid** [comment]
FWIW, Rawhide does have issues sometimes; are you okay with having a CI leg that (rarely) fails for days because the OS is broken?

Some things in Rawhide will hit us earlier than the constituent repos, and before they get a chance to fix the:

- RID issues (eg, just this week I ran into the `fedora.38-x64` RID)
- clang/gcc issues (eg, https://github.com/dotnet/runtime/pull/62170)
- Other system library (eg openssl) issues that come up only in the latest version of those libraries

**Comment by MichaelSimons** [comment]
[Triage]

1. It would be nice to not break the build on failures but have it as informational.  Always red or orange builds add no value.
2. We should be good stewards of the resources we consume.  Introducing an "outer ring" where we run these type of distros could be useful.  The outer ring would get run far less often.

**Comment by MichaelSimons** [comment]
The outer ring CI mentioned earlier is tracked with https://github.com/dotnet/source-build/issues/3463.

**Comment by MichaelSimons** [comment]
[Triage] In discussing this, we feel that ensuring we run CI on the latest Fedora release would be sufficient.  We should update the Fedora version in CI, get our CI policy documented in https://github.com/dotnet/source-build/issues/2813, and possible create a major release checklist that will help us ensure we are executing against our policy.
