### ISSUE TITLE
Nested .gitignores cause unexpected behavior when submodules are checked in

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3096]
In the "VMR-lite-lite" for .NET 6.0 and 7.0, submodules are checked-in. Imagine this situation:

```
.gitignore (A)
build/
submodules/
    submodule1/
        .gitignore (B)
        build/
```

```
.gitignore (A) contents:
build/

.gitignore (B) contents:
<does not ignore the build/ directory>
```

When the submodule is checked in, .gitignore (A) will combine with .gitignore (B), and thus `submodules/submodule1/build/` will be excluded. By the submodule1's original .gitignore, `build/` should have been included in the git repo.

@premun, you may encounter this with the VMR. If you are handling this already, what is your approach?

**Comment by premun** [comment]
@lbussell this is an interesting problem! I need to check what VMR does because I think we just got lucky there actually (read: "this didn't occur to me but the way we sync the code goes around this probably".

This is how it works when we synchronize code into the VMR:
- We clone the repo we are synchronizing into the VMR into TEMP outside of VMR's path
- We format the patch there and apply it onto the VMR (this way it adheres to the original `.gitignore` rules)
- We apply the patch and even though the files are ignored, if you check them in, they're in.

I need to verify this and also what happens when we change these files.

How to solve this?
- **Idea 1** - I know that there is this `!notation` which overrides the exclusion from before. Maybe we could add a `.gitignore` next to each inlined submodule and add there `!submodule-folder/**/*` item?
- **Idea 2** - We could technically also utilize the same tooling for VMR-lite-lite as for VMR-lite. I am fairly positive we could eventually hook up the -lite-lite onto the same process and just let it sync that way?

**Comment by MichaelSimons** [comment]
[Triage] Another possibility for the VMR lite and pre VMR lite would be to simply remove the .gitignores given the repos are readonly.

**Comment by premun** [comment]
> Another possibility for the VMR lite and pre VMR lite would be to simply remove the .gitignores given the repos are readonly.

I think removal of the `.gitignores` might not work well because I believe that if you would kick off builds from `src/runtime`, the `Directory.Build.props` there would create an `artifacts` dir in the `src/runtime` folder and we would ideally want that ignored.
But I think this is a complex problem and needs more experimentation.

Connected to this, I was reading about monorepo performance some time ago and `.gitignore` files are a big source of performance issues as the rules in them often have to be considered during various operations. Rules that are not rooted and contain wildcards are then expensive to match against the large tree of files and this kills perf of operations like `status` or `add` or `clean`.

I think one outcome of this might be the need to go around the repos and "tidying" these ignore rules. I think the `!notation` from **Idea 1** might work well too (but this needs an experiment).

**Comment by MichaelSimons** [comment]
> I think removal of the .gitignores might not work well

Agreed, this is only viable if the VMR is considered "read-only" where dev commits/PRs are not accepted.  That is certainly the case for the pre-VMR lite repo.

**Comment by premun** [comment]
Related to this - I guess we should add a `.gitignore` for the VMR too (to `tarball/content`). I will build the VMR tomorrow and check `git status`

**Comment by premun** [comment]
This only affects VMR once it's not read-only anymore and once devs will want to add new files into inlined submodules in the VMR, then they might hit this. I believe this should be fixed on the VMR tooling side where it would automatically maintain `.gitignore` files next to submodule folders.

I will add this into our project and track this. You can choose to untrack this it here, I'll leave that up to you.

**Comment by MichaelSimons** [comment]
[Triage] We don't see the ROI to address this in 6.0/7.0.  Closing.

**Comment by premun** [comment]
I logged https://github.com/dotnet/arcade/issues/12826 to track the possible VMR problems
