### ISSUE TITLE
Stop making src modifications to every repo's eng/common/tools.sh

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3171]
When building the VMR, there are several checked in files that are being modified. This yields a poor UX as these must be undone before you can build cleanly again. These edits will also become a nuisance in .NET 9 when the VMR can be used to checkin changes.

One type of file being modified is each repo's repo's eng/common/tools.sh. This file is updated to workaround https://github.com/dotnet/source-build/issues/2307

**Comment by NikolaMilosavljevic** [comment]
@MichaelSimons @mmitche - source-build is modifying `eng/common/tools.sh` to update the following line: https://github.com/dotnet/arcade/blob/f5d1610c0943aefc60193d26c43736b2c61a8ed6/eng/common/tools.sh#L512 to return `$exit_code` instead of `0`.

The following 2 environment variables are available during Bash script execution, and can be used to push the VMR change upstream, which would add some source-build conditioned code:
```
DotNetBuildFromSource=true
DotNetBuildFromSourceFlavor=Product
```

The alternative would be to dig deeper and understand if we could either: 1) drop source-build change altogether, or 2) modify Arcade's code to return `$exit_code`. Option 2 would run against the following comment and likely introduce extra logging noise - it's unknown if noise is all that would be added, or if some CI log-parsing code would fail. Here's the existing comment in Arcade: https://github.com/dotnet/arcade/blob/f5d1610c0943aefc60193d26c43736b2c61a8ed6/eng/common/tools.sh#L509-L512

**Comment by NikolaMilosavljevic** [comment]
> Does the history indicate why source-build changed to update this to return $exit_code?

It seems that this source-build workaround can simply be removed - https://github.com/dotnet/source-build/issues/2307#issuecomment-1313855686

cc @MichaelSimons

**Comment by MichaelSimons** [comment]
> It seems that this source-build workaround can simply be removed - https://github.com/dotnet/source-build/issues/2307#issuecomment-1313855686

This would need to be validated.  The exit code was not preserved and therefore would not fail the build.  SB runs with the CI flag set.

**Comment by NikolaMilosavljevic** [comment]
Besides workaround for https://github.com/dotnet/source-build/issues/2307, we also update `eng/common/tools.sh` to add another workaround for repos that are not using the latest Arcade: https://github.com/dotnet/installer/blob/1f0982b7f469aa0d693d1ad6744a7fde5263ef1b/src/SourceBuild/content/repo-projects/Directory.Build.targets#L67-L73

There are two repos that require this today: `command-line-api` and `xdt`.

**Comment by MichaelSimons** [comment]
> to add another workaround for repos that are not using the latest Arcade:

In .NET 9.0, I am hopeful that the VMR will force every repo to be on the same arcade version.  Ideally there would only be one copy of the eng/common directory in the VMR.

Shorter term, could we allow control via an ENV?

**Comment by NikolaMilosavljevic** [comment]
> > to add another workaround for repos that are not using the latest Arcade:
> 
> In .NET 9.0, I am hopeful that the VMR will force every repo to be on the same arcade version. Ideally there would only be one copy of the eng/common directory in the VMR.
> 
> Shorter term, could we allow control via an ENV?

We could utilize env.vars to condition this code. I presume the proposal is to make the necessary, conditioned, changes in `eng/common/tools.sh` of the affected repos, right?
