### ISSUE TITLE
Ensure release automation for security-partners works in .NET 8.0/VMR

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3194]
The ~~[recent change to introduce CI](https://github.com/dotnet/installer/pull/15007)~~ [recent pipeline added to mirror changes to the security partners repo](https://github.com/dotnet/source-build/blob/main/eng/source-build-release-mirror.yml) needs to be updates to work in the VMR.  There may be other changes needed with release automation - e.g. https://github.com/dotnet/source-build/blob/main/eng/source-build-pre-release.yml

**Comment by premun** [comment]
I saw the triage recording but I don't quite understand this task. The [linked pipeline](https://github.com/dotnet/installer/blob/release/7.0.1xx/src/SourceBuild/tarball/content/eng/pipelines/security-partners-dotnet.yml) seems to only build the tarball and I thought we have agreed that we don't need that as the VMR is validated in different places.

Or maybe I misunderstand what "release automation" means? Is this issue about mirroring the VMR too?

**Comment by premun** [comment]
I have also seen this one - https://github.com/dotnet/source-build/pull/3187 - should have this one been linked instead?

**Comment by premun** [comment]
Or is this about making sure the whole release checklist is applicable for the new VMR?

**Comment by MichaelSimons** [comment]
@premun - I link the wrong PR in the original description.  I updated the description.  I mean to link to the mirror pipeline.

**Comment by premun** [comment]
I think I have the code ready but to run it, I'd need to wait for the branch snap and some `release/8.0` build

https://github.com/dotnet/source-build/compare/prvysoky/net-8.0?expand=1

**Comment by premun** [comment]
I opened a PR to bring 8.0 up to par with 6.0/7.0


### Next steps
We could make the pipeline multi-stage and compose it of the various pipelines that need to be invoked separately. The stages could be divided by approval gates. So something like:
- **Get info stage** - Current pre-release pipeline
- **Approval gate** - Confirmation that smoke test prereqs are in place
- **Mirror stage** - Current mirroring pipeline
- **Approval gate** - Wait for .NET 8.0 release
- **Release stage** - Current release pipeline

We could then have 1 pipeline run for each release of each version (so a 6.0 run, 7.0 run, 8.0 run).

Only thing that is unclear is whether we have all the information in the beginning of the process. I found only one possible problem in a step that I don't fully understand: https://github.com/dotnet/source-build/blob/f93822b50a82dda6cc00bf545280c0a3f6f877a4/.github/ISSUE_TEMPLATE/releases/release_checklist.md?plain=1#L47
If I can get clarity on when this tag is created, we could answer this. The reason is that we cannot input further information once we kick off the pipeline. So it depends whether this tag is known in the beginning.

**Comment by premun** [comment]
Okay, closing this one as we got the preview out the door. Fallouts and follow-ups will be handled in different issues
