### ISSUE TITLE
Automate source-build partners content

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3196]
We send a monthly email to partners with information about pre-release repos, artifacts, and security updates. We should automate this with an outlook template, tool, or script so that the email content and recipients are consistent month-to-month and ensure we don't forget anything.

**Comment by lbussell** [comment]
Please note that the contents of this email could be considered sensitive.

**Comment by oleksandr-didyk** [comment]
Discussed the acceptable flow with @mthalman:

1. The pipeline should generate and publish the wiki, resolving everything that can be templated for cheap (like static links or version information)
2. As part of the Partners Notification approval stage, the user would be instructed to check the wiki and fill in information that the pipeline cannot currently resolve by itself (SAS token for accessing the published artifacts in an Azure storage container and a link to the CVEs resolved)
3. As part of the release stage, the pipeline would send out an e-mail to partners with basic release information as well as the link to the wiki published in step 1

Additionally, in long-term the manual intervention for the wiki page could be removed completely - for SAS token we potentially could publish to a different solution with a clearer access policy and for the CVE list we could add some tags pointing to the .NET version that will resolve the issue and have the pipeline fetch the links based on this tag

**Comment by oleksandr-didyk** [comment]
Waiting on https://github.com/dotnet/source-build/issues/3771

**Comment by mthalman** [comment]
This can definitely be done in a staged approach as well. Generation of the wiki page would be a good first step. Then generation of the email template. I'm not sure we'd want to automate the sending of the email since we'd want it to be sent from a member of the team and not some bot account.

**Comment by mthalman** [comment]
Yes, my concern was about the reply. I suppose that can be solved via the cc and a message in the email body stating that any reply should use "reply all".

**Comment by oleksandr-didyk** [comment]
> Waiting on #3771

PR for dependent issue finalized, work on this can be continued

**Comment by oleksandr-didyk** [comment]
Have working logic for creating and publishing the Wiki + building up the e-mail. Need to iron out some details and test the entire flow in the pipeline.

Was sidetracked a bit by the Christmas holidays, should have a PR for the work by the end of the week, 01.05

**Comment by oleksandr-didyk** [comment]
Pausing work on the issue to focus on higher-priority tasks for February release

**Comment by oleksandr-didyk** [comment]
After some discussions we think that it would better to separate the partner notification away from the main release pipeline.

This is primarily driven by the increase in release notifications making the flow a bit too chatty. Specifically, since in the current setup we run one build per major release, having the partner notifications in the release pipeline would result in one e-mail per major version and either one Wiki entry per major version or logic to handle creating / updating a singular Wiki page per release.

In addition, it may happen that one of the major version is lagging behind the expected release date (due to issues uncovered or some pending changes). This would cause an additional e-mail notifying the partners of the delay as well as the e-mail from the pipeline once it is released.

With all of this in mind, having a separate notification pipeline would provide us with better UX and cleaner communication with the partners. The idea would be that a source-build team member would simply select the releases a notification should be created for. The pipeline would then download the `source-build-manifest.json` files from selected releases to retrieve the information needed and create one Wiki page with one partner e-mail. For situations where additional context needs to be provided for a release (for example, if one of the servicing versions is delayed), the pipeline could accept some text input that would then get appended to the resulting e-mail.

@mthalman does this proposal make sense to you or do you have some extra comments to it? Thanks!

**Comment by mthalman** [comment]
Yes, I like this proposal. That will provide the best experience for partners.

**Comment by oleksandr-didyk** [comment]
I split the work into 3 parts to not introduce too much changes in a singular PR:
  - [x] Initial changes to `ReleaseCLI` to facilitate some of the commands the notifications pipeline will need
  	- https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37139
  - [ ] Adding the notifications pipeline, first part (gathering required release info, publishing Wiki page and generating the e-mail contents)
    - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37338
  - [ ] Adding sending of the e-mail after an approval gate

**Comment by oleksandr-didyk** [comment]
Agreed to have the e-mail sending part complete in `Preview 3`

**Comment by oleksandr-didyk** [comment]
Waiting on distribution email list for BCC

**Comment by oleksandr-didyk** [comment]
All PRs merged, closing
