### ISSUE TITLE
Error in source-build-release pipeline

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3255]
When running the source-build-release pipeline for the February servicing updates, I got this error in the `Get Associated Pipeline Run IDs` step of the Submit PR job:

`/mnt/vss/_work/_temp/cafb05ed-2c87-4c8b-afc9-77af68e2b4e0.sh: line 2: eng/get-build-info.sh: No such file or directory`

Builds: https://dev.azure.com/dnceng/internal/_build/results?buildId=2113787&view=logs&j=a9eab467-56d8-5e1c-5b62-7ab754c2b8e6&t=164fe4aa-146e-5c75-7060-5a4d0a808583, https://dev.azure.com/dnceng/internal/_build/results?buildId=2113726&view=logs&j=40cbf1a1-2796-59b0-4c06-98e7f6207d60&t=5984c123-cdc7-55ec-807c-7593c8655bef

**Comment by crummel** [comment]
cc @premun  I think you've been working in this area lately.

**Comment by premun** [comment]
Apologies for this. I think I broke the pipelines with the latest changes as I changed the pre-release pipeline but didn't know this piece of code is called from the release as well. Can you, as a quick workaround, run the release pipeline from an older commit and run the pipeline from there?

Let's say from `f93822b50a82dda6cc00bf545280c0a3f6f877a4`?

I believe it's the surest way to get unblocked because I believe there are more problems in the pre/release pipelines for 6.0/7.0 at the moment.

**Comment by MichaelSimons** [comment]
[Triage] This should be addressed with the new [unified build pipeline](https://github.com/dotnet/source-build/pull/3257).  @premun and @crummel can you work together to validate this is addressed with the new pipeline?  Also is there an issue tracking the removal of the old build definition?

**Comment by premun** [comment]
Yes, the new pipeline should work for 6.0/7.0 now. Dry runs for 7.0 were green but we never run them without that.

There's no issue for clean up yet. I wanted to discuss whether you're interested in preserving the runs that released the previous builds. I will log one.

**Comment by crummel** [comment]
This has been fixed with the unified release pipeline, closing.
