### ISSUE TITLE
7.0.103 source build regression?

### ISSUE THREAD

**Issue by alucryd** [dotnet/source-build#3262]
Hi guys, building the latest 7.0 release fails on Arch Linux without any change to our build recipe, did anything change on your end?

Full build log here: https://build.alucryd.xyz/#/builders/257/builds/342/steps/9/logs/stdio
Build recipe: https://github.com/archlinux/svntogit-community/blob/packages/dotnet-core/trunk/PKGBUILD

**Comment by lbussell** [comment]
Hi @alucryd, this error happens when the RID for the .NET SDK doesn't match the RID for the packages in the Private.SourceBuilt.Artifacts archive. Starting with .NET 7.0.101, our artifacts also no longer include portable packages due to https://github.com/dotnet/source-build/issues/3027 (our 7.0 artifacts are built with CentOS 8).

It appears your build definition isn't using the Arch Linux version of the 7.0.102 .NET SDK to build 7.0.103. Is that correct? If so, the build is probably using the Microsoft-built SDK which is always portable, which doesn't match up with our artifacts. Adding the `--bootstrap` argument to `prep.sh` might unblock you for this month. The option causes the script to automatically download portable versions of non-portable packages in the Private.SourceBuilt.Artifacts archive. You would add the option here: https://github.com/archlinux/svntogit-community/blob/packages/dotnet-core/trunk/PKGBUILD#L124

https://github.com/dotnet/source-build/issues/3222 should eliminate the need for the extra argument, and it should land in the next .NET source-build release.

**Comment by alucryd** [comment]
> Hi @alucryd, this error happens when the RID for the .NET SDK doesn't match the RID for the packages in the Private.SourceBuilt.Artifacts archive. Starting with .NET 7.0.101, our artifacts also no longer include portable packages due to #3027 (our 7.0 artifacts are built with CentOS 8).
> 
> It appears your build definition isn't using the Arch Linux version of the 7.0.102 .NET SDK to build 7.0.103. Is that correct? 

That's correct, I had a lot of issues in the past when bootstrapping using our own previous build, switching to yours was a lot smoother. I can give ours another try though if that's the preferred way.

> If so, the build is probably using the Microsoft-built SDK which is always portable, which doesn't match up with our artifacts. Adding the `--bootstrap` argument to `prep.sh` might unblock you for this month. The option causes the script to automatically download portable versions of non-portable packages in the Private.SourceBuilt.Artifacts archive. You would add the option here: https://github.com/archlinux/svntogit-community/blob/packages/dotnet-core/trunk/PKGBUILD#L124
> 
> #3222 should eliminate the need for the extra argument, and it should land in the next .NET source-build release.

Thank you, will give `--bootstrap` a try, and then explore bootstrapping with our own previous package again later on.

**Comment by alucryd** [comment]
That did the trick, thanks!
