### ISSUE TITLE
Release PR for .NET 8.0 doesn't update prebuilts/artifact versions correctly

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3344]
### Context

The release pipeline opens a PR against the installer repo and updates [VMR's `eng/Versions.props` file](https://github.com/dotnet/dotnet/blob/release/8.0.1xx-preview3/eng/Versions.props#L21-L23), specifically the part with prebuilt package versions.

These properties [changed](https://github.com/dotnet/installer/pull/15603) between 7.0 and 8.0 and need to be changed for 8.0 too.

### Goal

We need to have a look at the official VMR build associated with the release and find out the names of the artifacts from there and update the file using these names.

**Comment by tkapin** [comment]
@ali-turan7 - assigned this to you as it's close to the issues you've already implemented. 
@mthalman - could you please support @ali-turan7 in this if needed? Thanks

**Comment by mthalman** [comment]
@ali-turan7 - The two relevant URLs referenced in the Versions.props files are uploaded by these release pipeline steps:
https://github.com/dotnet/source-build/blob/d4f497340a69a09d6cb58b7fd8eba5a8cc27c74e/eng/templates/stages/release.yml#L344-L358

So basically, you just need to resolve what the names of those two files are. The file names are defined here:

https://github.com/dotnet/source-build/blob/d4f497340a69a09d6cb58b7fd8eba5a8cc27c74e/eng/templates/stages/release.yml#L84-L87

You can see that they use wildcards for the versions. (Actually, the artifacts file name doesn't use a wildcard yet. That change is coming in https://github.com/dotnet/source-build/pull/3451).

It's also important to note that the `$(sdkVersion)` variable can't be used here like it is for 6.0/7.0. Since, 8.0 is currently in preview, it doesn't use a stable version pattern and thus doesn't match what source-build produces. This is expected.

So an easy way to determine the version number used in the file is to resolve the wildcards locally on the build agent with a bash script using `basename`:

```yaml
- script: |
    set -euo pipefail
    resolvedSdkName=$(basename $(PIPELINE.WORKSPACE)/$(sdkArtifactFileName))
    echo "##vso[task.setvariable variable=ResolvedSdkName]$resolvedSdkName"
```

That script would set `ResolvedSdkName` to the actual file name with no wildcards in it. Then it's just a matter of using that value to replace what's in the Versions.props file. Since the pipeline already has the wildcard pattern for these two files, you could actually use those strings and dynamically convert them into a regular expression pattern that could then be passed to a `sed` command to do the replacement.

**Comment by mthalman** [comment]
Here's a sed command that can convert the wildcard pattern for the filename into a regular expression:

```
sed 's/\./\\./g; s/\*/.*/g'
```

This simply replaces all instances of `.` with `\.` and all instances of `*` with `.*`. For example, this would transform `Private.SourceBuilt.Artifacts.*.centos.8-x64.tar.gz` to `Private\.SourceBuilt\.Artifacts\..*\.centos\.8-x64\.tar\.gz`, the latter of which is a regular expression that is equivalent to the wildcard pattern of the former.

This regular expression can then be used to match the URL in the Versions.props file.

Here's something I typed up which demonstrates what I'm thinking (completely untested):

```bash
filenameRegex=$(echo "$(sourceBuiltArtifactsFileName)" | sed 's/\./\\./g; s/\*/.*/g')
actualFilename=$(basename <whatever>)

sed -i "s#\(<PrivateSourceBuiltArtifactsUrl>\).*$filenameRegex\(</PrivateSourceBuiltArtifactsUrl>\)#\1$actualFilename\2#" $versions_props_path
```

**Comment by ali-turan7** [comment]
In DryRun mode, the submit-sorce-build-release-pr script has been called.
In the final phase, right before raising the PR, the creation of the pull request has been disabled. 
The contents of the VersionsProps file were compared and printed to ensure that the desired changes were implemented correctly.
The results for each version are shown below.

Test for 8.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2184104&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd

Test for 7.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2185462&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd

Test for 6.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2185416&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd

**Comment by ali-turan7** [comment]
I ran another round of tests, and the outcomes are as follows:

Test for 8.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2186469&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=192

Test for 7.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2186471&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=201

Test for 6.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2186472&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=183

**Comment by mthalman** [comment]
> I ran another round of tests, and the outcomes are as follows:
> 
> Test for 8.0 https://dev.azure.com/dnceng/internal/_build/results?buildId=2186469&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=192
> 
> Test for 7.0 https://dev.azure.com/dnceng/internal/_build/results?buildId=2186471&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=201
> 
> Test for 6.0 https://dev.azure.com/dnceng/internal/_build/results?buildId=2186472&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=183

@ali-turan7 - It doesn't look like any of these show diffs in the output.

**Comment by mthalman** [comment]
So how do you verify the file is actually updated the expected content?

**Comment by ali-turan7** [comment]
I only verified if the parameters provided in the sed command were correct. I ran another round of tests, and the outcomes with diff are as follows: 

Test for 8.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2186633&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=194

Test for 7.0
https://dev.azure.com/dnceng/internal/_build/results?buildId=2186634&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=202

Test for 6.0 
https://dev.azure.com/dnceng/internal/_build/results?buildId=2186635&view=logs&j=19992227-62fb-5b50-4e29-3b72bd33eea1&t=9281c869-17dc-5ef7-6bc6-1c1da071debd&l=184

**Comment by mthalman** [comment]
Ok, looks good.
