### ISSUE TITLE
Provide a mechanism to gather prereq packages required to run smoke-tests offline

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3386]
The smoke-tests do not support running offline as they have a set of prereq packages.  The source-build infrastructure should provide a mechanism to gather these packages so that the tests can be run offline.  

The prep script script feels like the natural place for this to happen as it's primary responsibility is to gather the prereqs necessary to build.

**Comment by mthalman** [comment]
During development of https://github.com/dotnet/installer/pull/16359, it became clear that versions of dependent packages are being updated frequently enough that makes the maintenance of a baseline file unsustainable.

For that reason, a different approach needs to be taken. Rather than relying on the prep script that would need to be run to gather the smoke test prereqs, the proposal is that a tarball containining these prereqs is provided as part of the release assets. This tarball would contain all the necessary packages for building and running the smoke tests offline. It would need to consolidate all of the restored packages from the various architectures of build legs since there are architecture-specific packages included in the mix.

**Comment by mthalman** [comment]
@omajid / @mirespace - Please read the new approach I've described in https://github.com/dotnet/source-build/issues/3386#issuecomment-1583120095 and let me know your thoughts. Feel free to respond here if further clarification is needed.

Fundamentally, this isn't much different than what we do today for partner hand-off. This will just be automated as part of our release process. And the tarball that is produced will only include packages that are consumed by the smoke tests. Previously, we had been including some [additional packages](https://github.com/dotnet/source-build/blob/b9be5fbf2a037a002713bcb4ffec6527e1520425/test/GatherPackages.csproj#L13C1-L21) that weren't necessarily consumed by our smoke tests; those will no longer be included if the tests don't need them.

**Comment by dviererbe** [comment]
Hi @mthalman 👋🏻, we (Canonical) currently do not run the included smoke-tests automatically and as a consequence do not use the smoke test prereqs tarball either. But getting them working is on our Roadmap; I will put this issue on my TODO for next week.

The approach you proposed sounds good to me 👍🏻, if it should be more convenient for MS, I can also try Red Hat's approach and consume the NuGet feed directly.

**Comment by mthalman** [comment]
Use of the NuGet feed is more tricky because it requires knowing which packages the tests require. More packages exist in the feed than are actually used by the tests. That's one of the reasons why we're going with this tarball approach.
