### ISSUE TITLE
Release pipeline: Use public hosted agent pool for dry runs

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3401]
The release pipeline currently is configured to use the `NetCore1ESPool-Svc-Internal` agent pool which is the pool meant for internal releases. This pool is slower to provision agents than the public hosted pool like `ubuntu-latest`. This slows down the process of running test builds with the dry run option. We don't need to use the `NetCore1ESPool-Svc-Internal` pool for dry runs because we're not actually releasing anything.

**Comment by premun** [comment]
I was already thinking about this and wasn't sure we can afford this. We handle the same data, have the same tokens available and so on. So an insecure agent could leak all of this as easy.

I'd be happy to use hosted agents for PRs where we won't have any of this.

**Comment by premun** [comment]
@MichaelSimons @mthalman I'd vote to close this as I believe we cannot afford to do this.

On another note, the `1es-ubuntu-2004` we're using for most of the stages got a bit faster because they have changed the ephemerality of the disks recently but also it meant it broke the package mirroring (which we fixed afaik by switching over to a different queue)
