### ISSUE TITLE
Prodcon build output SHAs are updated to source-build automatically

### ISSUE THREAD

**Issue by dleeapho** [dotnet/source-build#342]
Every prodcon build presents a coherent set of repo states that produces a product build. We should take the SHAs in the manifest and update the submodule SHAs in source-build automatically.

**Comment by dagood** [comment]
PR https://github.com/dotnet/source-build/pull/371 to use the updater is created. Next steps are to create the Maestro subscription and a source-build general executor VSTS def to run the PR submission targets.

**Comment by dagood** [comment]
Here's the test submodule update to the ProdCon build: https://github.com/dotnet/source-build/pull/383. Didn't work, as expected, since our fixes aren't in the ProdCon branches yet.

I think I'll leave it open to soak up new ProdCon submodule updates. (It'll also get the BuildTools updates in it if someone makes a BuildTools release/2.1 change.)

/cc @dleeapho @dseefeld @crummel @weshaggard
