### ISSUE TITLE
Scan for binaries is failing from wasm file in runtime repo

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3442]
The CI build shows a warning in the `Scan for binaries` task:

```
./.dotnet/dotnet darc vmr scan-binary-files --vmr "/mnt/vss/_work/1/s" --tmp "/mnt/vss/_work/_temp" --baseline-file "src/VirtualMonoRepo/allowed-binaries.txt" || (echo '##[error]Found binaries in the VMR' && exit 1)
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /mnt/vss/_work/_temp/e45a5dcc-b89a-4f39-8e02-67abfa651e62.sh
src/runtime/src/mono/wasm/runtime/wasm-simd-feature-detect.wasm
##[error]Found binaries in the VMR
##[error]Bash exited with code '1'.
Finishing: Scan for binaries
```

**Comment by premun** [comment]
@kg can you share details on this new `wasm-simd-feature-detect.wasm` binary? I know we've already given an exemption to the previous one (https://github.com/dotnet/installer/blob/8488614afec7497b9e74b47c976af2a97506bb96/src/VirtualMonoRepo/allowed-binaries.txt#L50) and we had a tracking issue with that with a potential plan to replace it with something that is in an editable format.

Do you know if there are plans for these still?

**Comment by kg** [comment]
It's in the tracking issue, I haven't gotten to it yet since it requires me to author a new WASM compiler from scratch and integrate it into the build pipeline, which is probably a multi-day task for me. My understanding was that this doesn't currently cause any user pain, so I've been prioritizing issues with higher user impact. The new file is from the in-progress SIMD support, which we need to address multiple user-facing performance regressions due to increased vectorization in the BCL.
If the priority is higher than I understood, I can try to get it fixed after we branch for p5.

To be clear the new file is for feature detection of wasm vector128 support, since it wasn't in the MVP.

**Comment by premun** [comment]
> It's in the tracking issue

Can you share which issue so that we can link it to the suppression we will put in place?

**Comment by kg** [comment]
Near the bottom of https://github.com/dotnet/runtime/issues/78428
