### ISSUE TITLE
Stop running all CI legs on every checkin

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3463]
We should be good stewards of the amount of compute consumed by our CI.  Currently each checkin is consuming 8+ hours of compute.  We don't get a large amount of value from running each distro leg on every commit.  We should consider creating a new CI pipeline that is run on a less frequent schedule - e.g. once per weekday.  The CI run on every commit should contain the legs that have the highest ROI - e.g. online/offline, amd64/arm32, stage 1/2

**Comment by ellahathaway** [comment]
# Optimization of CI Pipeline Strategies

## The Problem

Currently, each check-in is consuming 8+ hours of computational resources. To optimize our processes, it's necessary to explore options that would allow the CI pipeline to operates on a less frequent schedule, perhaps once per weekday. It's proposed that the CI runs triggered by every commit should selectively include the distribution legs that yield the highest ROI. These could involve factors such as online/offline status, architecture (amd64/arm32), and the stage of the process (stage 1/2).

## End Goal

Our primary objective is to streamline our computational resource utilization while keeping a positive user experience at the forefront.

## Solutions

### Option 1: Multiple Pipelines

One approach is to establish two distinct CI pipelines.

**Heavy Pipeline:**
- **Schedule:** Once per weekday (12 am)
- **Tasks:** Computationally intensive processes
- **Distribution Legs:** All legs
- **Pros:**
  - Utilizes the full potential of computational resources during the dedicated run.
  - Comprehensive testing helps identify deep-seated issues that might not surface in 'lite' runs.

**Lite Pipeline:**
- **Schedule:** More frequent (every check-in)
- **Tasks:** Less computation-intensive tasks
- **Distribution Legs:** Highest ROI legs (online/offline, amd/arm32, stage 1/2)
- **Pros:**
  - Improved user experience due to clearer run status and distinct purposes of the pipelines.
  - Faster feedback loop as 'lite' runs occur more frequently.
  
**Cons:**
- More pipelines to monitor, potentially causing user confusion.
- Users will need to track yet another pipeline alongside the existing ones.
- Managing two separate pipelines might increase administrative overhead.

### Option 2: Single Pipeline

Alternatively, the current single pipeline can be retained, but its runs can be categorized by schedule.

**Full Runs:**
- **Schedule:** Once per weekday (12 am)
- **Tasks:** Comprehensive testing, resource-intensive computations
- **Distribution Legs:** All legs
- **Pros:**
  - Detailed testing helps ensure the stability of the entire system.
  - Dedicated 'full' runs provide a holistic view of the system's health.

**Lite Runs:**
- **Schedule:** More frequent (every check-in)
- **Tasks:** Less computation-intensive tasks
- **Distribution Legs:** Highest ROI legs (online/offline, amd/arm32, stage 1/2)
- **Pros:**
  - Centralized monitoring in a single pipeline simplifies user experience.
  - Users do not need to navigate through multiple pipelines, reducing potential confusion.

**Cons:**
- Determining whether a run was 'full' or 'lite' could be challenging, potentially leading to confusion.
- The current pipeline's interface might become cluttered due to the inclusion of additional information.
- Managing different run types within the same pipeline might require more sophisticated tracking mechanisms.

In either approach, the decision hinges on striking a balance between computational efficiency and user-friendliness. I am personally in favor of Option 1 (multiple pipelines), but I'd like to hear other opinions on the options & if anyone has thoughts on additional options not mentioned above.

**Comment by MichaelSimons** [comment]
I lean toward Option 1 as well as I think the confusion con of Option 2 is significant and could end up causing a lot of badness - e.g. thinking we are green to ship when in fact we are not.

**Comment by ellahathaway** [comment]
In looking through the legs, I've realized that most are titled with "Online/offline", making it difficult for me to differentiate which legs should be included in the list of the highest ROI. Below is a running list of legs per pipeline that I've come up with. Thoughts?

Lite:
- CentOSStream8_Online_MsftSdk
- CentOSStream8_Offline_MsftSdk
- Alpine317_Offline_MsftSdk
- Fedora38_Offline_MsftSdk
- Ubuntu2204_Offline_MsftSdk
- Ubuntu2204Arm64_Offline_MsftSdk
- CentOSStream8_Online_CurrentSourceBuiltSdk
- Fedora38_Offline_CurrentSourceBuiltSdk

Not included in Lite (will be in the heavy pipeline + the legs in the lite pipeline):
- CentOSStream8_Online_PreviousSourceBuiltSdk
- CentOSStream8_Offline_PreviousSourceBuiltSdk
- CentOSStream9_Offline_MsftSdk
- CentOSStream8_Mono_Offline_MsftSdk

**Comment by mthalman** [comment]
Here's my thinking...

Lite:
CentOSStream8_Online_MsftSdk
CentOSStream8_Online_PreviousSourceBuiltSdk
Fedora38_Offline_MsftSdk

Heavy:
Alpine317_Offline_MsftSdk
Ubuntu2204_Offline_MsftSdk
Ubuntu2204Arm64_Offline_MsftSdk
CentOSStream8_Online_CurrentSourceBuiltSdk
CentOSStream8_Offline_MsftSdk
CentOSStream8_Offline_PreviousSourceBuiltSdk
CentOSStream8_Mono_Offline_MsftSdk
CentOSStream9_Offline_MsftSdk
Fedora38_Offline_CurrentSourceBuiltSdk

The thing to note is that CentOSStream8_Online_PreviousSourceBuiltSdk requires assets from CentOSStream8_Online_MsftSdk and CentOSStream8_Offline_PreviousSourceBuiltSdk requires assets from CentOSStream8_Offline_MsftSdk. So those pairs shouldn't be split apart.

For lite, I do want the stage 2 bootstrap scenario covered, which is what CentOSStream8_Online_MsftSdk/CentOSStream8_Online_PreviousSourceBuiltSdk gives you. Then adding an offline build (Fedora38_Offline_MsftSdk) with a different distro gives you extra coverage. Plus, Fedora38_Offline_MsftSdk gives you poison test validation.

I'm sure @MichaelSimons has his own thoughts on this.

**Comment by MichaelSimons** [comment]
There are some subtle differences between the legs that are important when considering which legs to run on each checkin.  These subtle differences are controlled by the leg input parameters,  The following are the possible scenario permutations we can have.

Online/Offline 
Poison enabled
amd64/arm64
musl/gcc (alpine/all other distros)
Stage1/Stage2
CoreCLR/Mono
Distro variants

With these scenarios in mind, it is a matter of how to minimize the legs in order to maximize the coverage in conjunction with how much compute we want to consume on each checkin.  Today we run 12 legs.

To maximum the coverage and cutting the legs in half we could run the following on each checkin:

CentOSStream8_Online_MsftSdk (stage1/online/gcc/coreclr/amd64)
CentOSStream8_Online_CurrentSourceBuiltSdk  (stage2/online/gcc/coreclr/amd64)
Fedora38_Offline_CurrentSourceBuiltSdk (stage1/offline/gcc/amd64/coreclr/poison)
Alpine317_Offline_MsftSdk (stage1/offline/musl/coreclr/amd64)
Ubuntu2204Arm64_Offline_MsftSdk (stage1/offline/gcc/coreclr/arm64)
CentOSStream8_Mono_Offline_MsftSdk (stage1/offline/gcc/mono/arm64)

I still feel like this is too much on each checkin.  Given that, perhaps we should come to an agreement on how much compute we want to spend first.  

Another thought is that perhaps this policy has to be more dynamic.  By that I mean in release branches during the final builds, we want the full validation to run immediately.  In main, we don't need to or want to consume this much compute on each checkin.

**Comment by MichaelSimons** [comment]
Discussing this in standup, the following proposal was floated:

CentOSStream8_Online_MsftSdk (stage1/online/gcc/coreclr/amd64)
CentOSStream8_Online_CurrentSourceBuiltSdk (stage2/online/gcc/coreclr/amd64)
Alpine317_Offline_PreviousSourceBuiltSdk (stage1/offline/musl/amd64/coreclr/poison)

This would require some changes to our current legs.  We would start running poison on the alpine leg and refactor it to build with the PreviousSourceBuiltSdk.  This would help us maximize scenario coverage with the fewest legs.

**Comment by MichaelSimons** [comment]
@ellahathaway - what work remains now before this issue can be closed?

**Comment by ellahathaway** [comment]
The issue can be closed. I'll close it now.
