### ISSUE TITLE
Smoke tests failing for ppc64le mono source build for .net8

### ISSUE THREAD

**Issue by Swapnali911** [dotnet/source-build#3548]
Repro Steps: 
1. Clone the VMR or create a Codespace: https://github.com/dotnet/dotnet
2. Untar bootstrap sdk in .dotnet folder under dotnet
3. Copy cross built nupkg to the prereqs/packages/prebuilt/  
4. Update dotnet version in the global.json
5. Prep the VMR: Run https://github.com/dotnet/dotnet/blob/main/prep.sh
6. Build the VMR: Run https://github.com/dotnet/dotnet/blob/main/build.sh with --use-mono-runtime
7. Runtime smoke tests for built sdk : `./build.sh --run-smoke-test`

Currently, BasicScenarioTests, WebScenarioTests are failing for .net8 preview builds

Expected : Smoke tests should be skipped.

cc : @omajid  @tmds @Sapana-Khemkar @janani66
[smoke_test logs.txt](https://github.com/dotnet/source-build/files/11979259/smoke_test.logs.txt)

**Comment by Swapnali911** [comment]
[xUnit.net 00:00:37.36]     Microsoft.DotNet.SourceBuild.SmokeTests.BasicScenarioTests.VerifyScenario(scenario: TestScenario { Commands = Build | Run | PublishComplex | PublishR2R, Language = CSharp, NoHttps = False, ScenarioName = "BasicScenarioTests", Template = Console }) [FAIL]
    [xUnit.net 00:00:44.82]     Microsoft.DotNet.SourceBuild.SmokeTests.WebScenarioTests.VerifyScenario(scenario: TestScenario { Commands = Build | Run | PublishComplex, Language = CSharp, NoHttps = False, ScenarioName = "WebScenarioTests", Template = Web }) [FAIL]
	[xUnit.net 00:02:07.34]     Microsoft.DotNet.SourceBuild.SmokeTests.WebScenarioTests.VerifyScenario(scenario: TestScenario { Commands = Build | Run | PublishComplex, Language = FSharp, NoHttps = False, ScenarioName = "WebScenarioTests", Template = Web }) [FAIL]
	[xUnit.net 00:02:16.65]     Microsoft.DotNet.SourceBuild.SmokeTests.BasicScenarioTests.VerifyScenario(scenario: TestScenario { Commands = Build | Run | PublishComplex | PublishR2R, Language = FSharp, NoHttps = False, ScenarioName = "BasicScenarioTests", Template = Console }) [FAIL]
	Line 309:   [xUnit.net 00:02:37.74]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: Mvc) [FAIL]
	[xUnit.net 00:04:21.23]     Microsoft.DotNet.SourceBuild.SmokeTests.BasicScenarioTests.VerifyScenario(scenario: TestScenario { Commands = Build | Run | PublishComplex | PublishR2R, Language = VB, NoHttps = False, ScenarioName = "BasicScenarioTests", Template = Console }) [FAIL]
	[xUnit.net 00:05:14.18]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: Console) [FAIL]
	[xUnit.net 00:07:50.63]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: ClassLib) [FAIL]
	[xUnit.net 00:10:27.18]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: WebApp) [FAIL]
	[xUnit.net 00:13:03.60]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: MSTest) [FAIL]
	[xUnit.net 00:15:40.16]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: Web) [FAIL]
	[xUnit.net 00:18:16.67]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: Worker) [FAIL]
	[xUnit.net 00:20:53.19]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: NUnit) [FAIL]
	[xUnit.net 00:23:29.63]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: XUnit) [FAIL]
	[xUnit.net 00:26:06.26]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: WebApi) [FAIL]
	[xUnit.net 00:28:42.72]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario(template: BlazorWasm) [FAIL]

**Comment by mthalman** [comment]
For documentation purposes, there are two types of failures going on:

* OmniSharp tests fail when attempting to get an OmniSharp tarball for the given the architecture. In this case, there is no omnisharp-linux-ppc64le.tar.gz.
* Basic and Web tests fail attempting to restore RID-specific NuGet packages based on the architecture. For example, `error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.linux-ppc64le. No packages exist with this id in source(s): dotnet-public, dotnet8, dotnet8-transport`. These packages don't exist for ppc64le.

I agree that the OmniSharp test should be skipped since there's no available ppc64le OmniSharp tarball. But for the other tests that are missing, shouldn't the solution be to set a custom feed location, via the `SMOKE_TESTS_CUSTOM_PACKAGES_PATH` environment variable, that does provide these packages rather than skipping the tests entirely?

**Comment by Swapnali911** [comment]
@mthalman Thanks for the information. I will check with `SMOKE_TESTS_CUSTOM_PACKAGES_PATH` for BasicScenarioTests and WebScenarioTests and update.

**Comment by tmds** [comment]
> Microsoft.NETCore.App.Runtime.linux-ppc64le

This is a portable rid. Such packages are built by Microsoft, but not in this case because this architecture is community only.

The tests using there runtime packages should be skipped for ppc64le and s390x.

Note that the runtime packages that are source built have non-portable rid, like `rhel.8-ppc64le`. Their use-cases are different from portable rids, so they are distinct test-cases.

**Comment by MichaelSimons** [comment]
[Triage] @Swapnali911 - is the conditioning of the omnisharp and scenario tests something you would be willing to contribute a fix for?

**Comment by Swapnali911** [comment]
@MichaelSimons I am not aware where the changes would be require to skip omnisharp and other sceranios for ppc64le. I will look into the code and will try on this.

**Comment by Swapnali911** [comment]
I am able to skip OmniSharp tests for ppc64le arch using SkippableFactAttribute

```
  [xUnit.net 00:00:00.60]     Microsoft.DotNet.SourceBuild.SmokeTests.OmniSharpTests.VerifyScenario [SKIP]
  [xUnit.net 00:00:00.60]       Skipping because arch is `ppc64le`
```

Currently failure status is 
  Total tests: 27
       Passed: 20
       Failed: 5
      Skipped: 2
 
For Omnisharp I will raise a PR after getting it reviewed internally.
Checking on remaining failures for BasicTestScenarios and WebScenarioTests
