### ISSUE TITLE
GC vulnerability related to System.Security.Cryptography.Pkcs 7.0.0 & 6.0.1 presence 

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/source-build#3576]
### Describe the Bug

The source build project is used as a part of MSBuild project.
Now we receive 2CG issues due to existing refs to System.Security.Cryptography.Pkcs 7.0.0 & 6.0.1.

### Steps to Reproduce
https://dev.azure.com/dnceng-public/public/_build/results?buildId=360310&view=logs&j=c316b76e-5b95-5e79-2740-62e92f13eebd&t=6a1059ce-1250-5449-afb1-dfba4ab7893f&l=2978

**Comment by MichaelSimons** [comment]
[Triage] The uber problem of CG alerts being raised for package that are not referenced directly that come from because https://github.com/dotnet/source-build-reference-packages will be addressed by the changes made in https://github.com/dotnet/arcade/pull/13935.

Will keep this issue open to address these CG alerts once all product references to these packages have been removed.

**Comment by YuliiaKovalova** [comment]
Thank for resolving it.
