### ISSUE TITLE
[VMR] Design and implement way of building parts of the subgraph based on platform/scenario

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3682]
### Describe the Problem

There are some repos that we do not need to build, based on the platform we are building, or the compliance requirements of the build. For instance:
- No need to build Windows desktop repos for Linux
- No need to build SBRP/SBE except when building in context of RH/Canonical (SB strict?)

### Describe the Solution

The repo projects contain the build graph. This list should be filtered based on inputs to the build. Perhaps:
- TargetOS
- Build org?

Design and implement such a solution.

**T-Shirt size: Small**

**Comment by mmitche** [comment]
T-Shirt size: Medium

**Comment by ViktorHofer** [comment]
Agreed. `TargetOS` and `DotNetBuildFromSource` (or the new equivalent in the future) make most sense here.

**Comment by ViktorHofer** [comment]
This is already implemented in the Windows PoC. Keeping this open until we get the orchestrator changes merged into installer.

**Comment by mmitche** [comment]
Reopening this. We should have a more complete implementation of this that takes into account things like short vs. tall stacks.

**Comment by ViktorHofer** [comment]
Requirements:
- Identify which repos actually need to build assets that contribute to the product for the given short stack vertical. Is it really just runtime (+ dependencies)?
- Build locally, validate manually the build is successful and expected artifacts are produced. This probably requires (small) updates in the orchestrator and probably in runtime.
- After https://github.com/dotnet/source-build/issues/3823, add legs for the tested short stack verticals to the pipeline.

**Comment by directhex** [comment]
https://github.com/dotnet/installer/pull/18463 represents the current status of work on this.

It's tested with android-x64, android-arm64, and browser-wasm runtime packs.

wasi-wasm is bugged and requires a runtime patch https://github.com/dotnet/runtime/pull/98004

iossimulator-x64 and other Mac variants are bugged locally, apparently due to toolchain change surprised from Apple, but may be fine in CI (this will need a runtime patch to work around the new Apple linker, but that's not VMR's responsibility)
