### ISSUE TITLE
VMR output and intermediate directory names need a rework

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3696]
### Describe the Bug

When working on a cross-build for Linux, @directhex noted that the blob feed and artifacts directories still specify x64: https://github.com/dotnet/source-build/issues/3671#issuecomment-1783079761. We should rework these directory names.

### Steps to Reproduce

See https://github.com/dotnet/source-build/issues/3671#issuecomment-1783079761 for info.

### Other Information

My guess is that the target arch should be in the name of the directory, rather than the host. Furthermore, it may make sense to change 'blob-feed' to something meaningful (intermediate-assets?). 'blob-feed' refers to a bit of ancient technology we used to use for NuGet feeds in the 2.1 timeframe (Sleet).

**T-Shirt size: XS**

**Comment by mmitche** [comment]
T-Shirt size: Small, not critical

These changes should be relatively simple?

**Comment by ViktorHofer** [comment]
Note that `TargetArchitecture` is already encoded in the directory name. I think this issue comes from not using the GNU terms correctly in the various repositories and now also having a `OverrideTargetOS` setting. We should simplify those various models. I expect the folder structure to be automatically fixed when doing that.

Overall I agree that what this issue tracks is not critical and just a cosmetic change.
