### ISSUE TITLE
Investigate SBRP poison leaks

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3775]
Detected two SBRP poison leaks of when building locally. These should be investigated.
```
<PrebuiltLeakReport>
  <File Path="artifacts/x64/Release/dotnet-sdk-9.0.100-alpha.1.23607.1-ubuntu.22.04-x64.tar.gz/sdk/9.0.100-alpha.1.23607.1/DotnetTools/dotnet-format/Microsoft.Bcl.AsyncInterfaces.dll">
    <Hash>284daa41505d15084ed612d1e6af070847770f7bc0518b44c1ab9f0d58a771e6</Hash>
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.9.0.100-alpha.1.23607.1.ubuntu.22.04-x64.tar.gz/dotnet-format.9.0.457401.nupkg/tools/net9.0/any/Microsoft.Bcl.AsyncInterfaces.dll">
    <Hash>284daa41505d15084ed612d1e6af070847770f7bc0518b44c1ab9f0d58a771e6</Hash>
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
</PrebuiltLeakReport>
```

**Comment by ellahathaway** [comment]
Took a quick look into this, and it appears that these leaks should have been resolved with https://github.com/dotnet/format/pull/1975. It seems like they may have been re-introduced by https://github.com/dotnet/format/commit/03e4fb2314f5f2f2a9635f3c8a6c9ab5d55c3d16.

@mthalman What are your thoughts on this?

**Comment by ViktorHofer** [comment]
Yes, that's probably because of https://github.com/dotnet/format/commit/03e4fb2314f5f2f2a9635f3c8a6c9ab5d55c3d16. I removed this block because there was no indication in source that the entry was still required. It just looked like dead-code. We should bring it back but add a comment marker explaining why this is necessary.

In general, any Version.Details.xml entry in the stack that doesn't have a comment marker and isn't actively used in source is subject of removal during clean-up.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/format/pull/2048
