### ISSUE TITLE
VMR build fails with unrecognized TargetFramework for LeakDetection project

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3812]
Build fails with the following error in the `Alpine317_Offline_PreviousSourceBuiltSdk_x64` build leg:

`
/vmr/.dotnet/sdk/9.0.100-alpha.1.23603.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(96,5): error NETSDK1013: The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [/vmr/eng/tools/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection.csproj]
`

This seems to be due to the removal of the hardcoding of `NetCurrent` at the root of the VMR in https://github.com/dotnet/installer/pull/17987.

It's not clear to me why this only happens in this build leg though.

**Comment by ellahathaway** [comment]
It appears that `Microsoft.NET.TargetFrameworkInference.targets` is [only supposed to be included if if `TargetFramework` is set](https://github.com/dotnet/dotnet/blob/aa6cc254962a3b163c807485a1d7183b4a4235d0/src/sdk/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L15), so I'm not sure why this file is being evaluated if `TargetFramework` is `''` as the error suggests.

**Comment by ellahathaway** [comment]
Confirmed that is error is occurring because of the removal of hardcoding `NetCurrent`.

[This task uses `NetCurrent` to set the target framework](https://github.com/dotnet/dotnet/blob/83c42b62bf805c6a376be3f00ae7269e665001ed/eng/tools/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection.csproj#L4), and `Microsoft.NET.TargetFrameworkInference.targets` fails when attempting to evaluate it because it's empty.

What's odd to me here is that `Microsoft.NET.TargetFrameworkInference.targets` is [only supposed to be included if TargetFramework is set](https://github.com/dotnet/dotnet/blob/aa6cc254962a3b163c807485a1d7183b4a4235d0/src/sdk/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L15) per the comment at the top of the file. I noticed that it is being imported by [`sdk/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets` unconditionally](https://github.com/dotnet/dotnet/blob/83c42b62bf805c6a376be3f00ae7269e665001ed/eng/tools/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection.csproj#L4). Is `Microsoft.NET.TargetFrameworkInference.targets` supposed to be conditionally imported? Is it supposed to always be imported and run despite the state of TargetFramework? The comment feels misleading to me given my investigation thus far.

> It's not clear to me why this only happens in this build leg though.

The reason that this occurs in this build leg and not all the others is because this leg is the only leg that has poisoning enabled.

**Comment by ellahathaway** [comment]
https://github.com/dotnet/dotnet/blob/9e1871e4b8a2a260b00a083a25e1e0fa2d84b779/eng/tools/Directory.Build.props#L8 prevents leak detection and other tooling from using the Arcade sdk & thus the `NetCurrent` set by Arcade.

As a result, I can either 1) remove this line and import the arcade SDK, 2) hardcode `NetCurrent` back in `src/SourceBuild/content/Directory.Build.props`, or 3) hardcode net9.0 as the target framework for the tasks that use `NetCurrent` (LeakDetection and XPlat) in their respective .csproj files.

@mthalman What are your thoughts?

**Comment by mthalman** [comment]
I don't know the implication of using the Arcade SDK. # 2 is the best option because it keeps everything consolidated to a single property definition.
