### ISSUE TITLE
Implement VMR PR pipeline

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3823]
We have a PR pipeline today based out of the installer repo. This will need to move to the VMR repo.

**T-Shirt Size: Small**

**Comment by ViktorHofer** [comment]
It looks like we already have a PR pipeline in dotnet/dotnet: https://github.com/dotnet/dotnet/pull/46

**Comment by ViktorHofer** [comment]
Requirements:
1. Add a few initial legs for building without building from source on Windows, Ubuntu and macOS
2. Add those legs to the installer PR
3. Also run them as official builds so that we can compare the produced assets with the current Windows official build
4. Disable repos that currently don't build when not building from source via an exclusion mechanism.

**Comment by mmitche** [comment]
Marking as Ready

**Comment by akoeplinger** [comment]
This was done.
