### ISSUE TITLE
Remove binary cloaks from the VMR's main branch

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4087]
There is a shared desire to build both the Microsoft flavor of .NET as well as all of the source-build distro versions from the same source (one repo/commit/tag).   To support this binaries will be allowed within the VMR going forward but require an explicit action.  The current set of OSS-license binaries will be allowed wholesale as to not hinder the Unified Build project.

When doing this work, it is important to preserve cloaks that remove non-oss licensed components e.g. https://github.com/dotnet/installer/blob/main/src/VirtualMonoRepo/source-mappings.json#L193.

As part of this work, it will have to be decided what to do with the binary scan detector.  That tool may still be needed by https://github.com/dotnet/source-build/issues/4089

**Comment by ellahathaway** [comment]
I'm thinking that we should keep the binary scanner. It will be necessary in preventing any new and unwanted binaries in the VMR. However, I'd like to modify the scanner to use the source-mapping file rather than the allowed-binaries.txt. The reasoning for this is that a developer would only have to touch a single file if they decide to include or cloak a file. Using source-mapping file, the binary scanner will search for any binaries not explicitly listed as "includes".

**Comment by premun** [comment]
Yeah, this sounds like a good plan to me. It should be fairly straightforward to extend the file model and transition onto it.

The scan itself was implement by @dkurepa but we're both able to assist with the changes. There are even E2E tests in the `arcade-services` repo which execute everything on a local VMR so this should help validate everything upfront.

**Comment by MichaelSimons** [comment]
> The scan itself was implement by @dkurepa but we're both able to assist with the changes. There are even E2E tests in the arcade-services repo which execute everything on a local VMR so this should help validate everything upfront.

I wonder if there is value in pulling this outside of arcade-services so that is can be run by distro-maintainers in their source-build environment?  e.g. treat is more as a smoke-test.
