### ISSUE TITLE
Promote the source-build's license scan pipeline to be a general VMR pipeline

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4091]
This is related to https://github.com/dotnet/source-build/issues/4088.

This includes:

1. Renaming the pipeline/yml to not be source-build specific.
    - https://github.com/dotnet/installer/pull/19201
1. Examine the feasibility of running the scan on flows into the VMR or at the repo level.
   - https://github.com/dotnet/source-build/issues/4267

**Comment by ellahathaway** [comment]
Updating this issue:

1. Renaming the pipeline/yml to not be source-build specific.
  - We should rename the pipeline to something that is not source-build specific
  - The pipeline makes use of ./prep-source-build.sh. Since this is a source-build specific script, we should evaluate if we should/need to still make use of this script in the pipeline. 
 
2. Examine the feasibility of running the scan on flows into the VMR or at the repo level.
  - This is a bigger issue. Since the scanning, like the binary tool, relies on cloaks, we need to determine if it is feasible to cloak at the repo level first.
  - The determination on the cloaking will determine the actionability of this work item.

**Comment by ellahathaway** [comment]
Based on https://github.com/dotnet/source-build/issues/4267, it seems like we have decided to implement the license scan at the repo level. Therefore, I'm saying that `Examine the feasibility of running the scan on flows into the VMR or at the repo level` has been accomplished.

Marking this issue as closed.
