### ISSUE TITLE
Poison leak from dotnet tools

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4116]
```xml
<PrebuiltLeakReport>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/Microsoft.Win32.SystemEvents.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-format/System.Drawing.Common.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/dotnet-sdk-x.y.z/sdk/x.y.z/DotnetTools/dotnet-watch/x.y.z/tools/netx.y/any/System.Drawing.Common.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/Microsoft.Win32.SystemEvents.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
  <File Path="artifacts/x64/Release/Private.SourceBuilt.Artifacts.x.y.z/dotnet-format.x.y.z/tools/netx.y/any/System.Drawing.Common.dll">
    <Type>SourceBuildReferenceAssembly</Type>
  </File>
</PrebuiltLeakReport>
```

**Comment by mthalman** [comment]
I believe this is caused by Roslyn's migration to Central Package Versioning in https://github.com/dotnet/roslyn/pull/71111.

This DLLs are being leaked into the source built output as a result of dotnet tools dependency on `Microsoft.CodeAnalysis.Workspaces.MSBuild`. We can look at the content of the project.assets.json file of the depending projects to give some hints at what is going on.

Prior to the regression:

```json
"Microsoft.CodeAnalysis.Workspaces.MSBuild/4.10.0-1.24067.21": {
  "type": "package",
  "dependencies": {
    "Microsoft.Build": "17.3.2",
    "Microsoft.Build.Framework": "17.3.2",
    "Microsoft.Build.Tasks.Core": "17.3.2",
    "Microsoft.CodeAnalysis.Common": "[4.10.0-1.24067.21]",
    "Microsoft.CodeAnalysis.Workspaces.Common": "[4.10.0-1.24067.21]",
    "Microsoft.Extensions.Logging.Abstractions": "9.0.0-preview.2.24080.1",
    "Newtonsoft.Json": "13.0.3",
    "System.Text.Json": "9.0.0-preview.2.24080.1"
  },
```

Latest:

```json
"Microsoft.CodeAnalysis.Workspaces.MSBuild/4.10.0-2.24112.4": {
  "type": "package",
  "dependencies": {
    "Humanizer.Core": "2.14.1",
    "Microsoft.Build": "17.3.2",
    "Microsoft.Build.Framework": "17.3.2",
    "Microsoft.Build.Tasks.Core": "17.3.2",
    "Microsoft.CodeAnalysis.Common": "[4.10.0-2.24112.4]",
    "Microsoft.CodeAnalysis.Workspaces.Common": "[4.10.0-2.24112.4]",
    "Microsoft.Extensions.Logging.Abstractions": "9.0.0-preview.2.24112.33",
    "Newtonsoft.Json": "13.0.3",
    "System.Buffers": "4.5.1",
    "System.CodeDom": "7.0.0",
    "System.Collections.Immutable": "9.0.0-preview.2.24112.33",
    "System.Composition": "9.0.0-preview.2.24112.33",
    "System.Configuration.ConfigurationManager": "7.0.0",
    "System.Drawing.Common": "7.0.0",
    "System.IO.Pipelines": "9.0.0-preview.2.24112.33",
    "System.Memory": "4.5.5",
    "System.Reflection.Metadata": "9.0.0-preview.2.24112.33",
    "System.Resources.Extensions": "7.0.0",
    "System.Runtime.CompilerServices.Unsafe": "6.0.0",
    "System.Text.Encoding.CodePages": "7.0.0",
    "System.Text.Json": "9.0.0-preview.2.24112.33",
    "System.Threading.Channels": "7.0.0",
    "System.Threading.Tasks.Dataflow": "7.0.0"
  },
```

Obviously a bunch more dependencies are included, including the problematic one, `System.Drawing.Common`, which also brings in `Microsoft.Win32.SystemEvents`. The difference is that the latest one is explicitly declaring these extra packages as dependencies rather than implicitly transitive. How can we get it configured like it was prior to the regression?

/cc @tmat, @jasonmalinowski, @ViktorHofer

**Comment by ViktorHofer** [comment]
I think this is because of transitive pinning: https://github.com/dotnet/roslyn/blob/d5fe410cbcbccc1b122e93f4bf4cf5bf66260f90/Directory.Packages.props#L4

dotnet/sdk and couple other repos use that functionality as well

**Comment by jasonmalinowski** [comment]
@ViktorHofer Your comment makes this sound like this is a known issue with that feature, or something else?

Otherwise to understand the dependency chain here: the Microsoft.Build.* packages we use depend on [System.Configuration.ConfigurationManager 6.0.0](https://www.nuget.org/packages/System.Configuration.ConfigurationManager/6.0.0). It seems as a part of our changes we lifted that up to 7.0, which has the problematic chain in the framework versions: System.Configuration.ConfigurationManager version 7 depends on System.Security.Permissions, which depends on System.Windows.Extensions, which depends on (at least in the 7.0 line) System.Drawing.Common. That last jump is definitely surprising but was fixed in 8.0 with https://github.com/dotnet/runtime/pull/88157.

If this is a bug in transitive pinning we should just fix that. Otherwise @ViktorHofer what specifically is the problem that we need to fix here? If it's just "don't have a reference on System.Drawing" we could bump some versions up to the 8.0 to get that fix. If those other references are also problematic then we'll need a more general solution.

**Comment by ViktorHofer** [comment]
No, this isn't a problem in the NuGet CPM transitive pinning implementation. This is related to your usage of CPM which apparently causes issues in source-build.

**Comment by MichaelSimons** [comment]
[Triage] Fix was made to roslyn, waiting for it to flow to validate fix.

**Comment by mthalman** [comment]
Confirmed this fixed now in latest builds.
