### ISSUE TITLE
Release pipeline PR validation doesn't test build tagging scenario

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4121]
The changes in https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37227 (internal link) fix an issue that occur where Arcade update the tagging pattern for pipeline runs of the VMR. It changed from `installer-<sha>` to `installer <sha>`. What's notable is that the PR validation for the release pipeline doesn't execute the code path which causes this build tag to be queried. So we really have no way to verify that the logic is correct today.

This is a more general problem of different code paths within the release pipeline based on certain configurations.

**Comment by MichaelSimons** [comment]
[Triage] Can we have one implementation that looks up the build?  e.g. eliminate the multiple tags?

**Comment by oleksandr-didyk** [comment]
There doesn't seem to be an easy way to resolve this from the standpoint of the pipeline.

Technically we have two situations for finding the VMR build being released:
  - we get the installer commit from `Stage-DotNet` and there is a CI VMR build syncing to this commit
  - we get the installer commit from `Stage-DotNet` but:
    - this commit was rolled over by the VMR CI (it synced to some child commit)
    - we explicitly want to use a different VMR CI build
 
If the commit was rolled over, we want to fail and let the user know they have to run the CI for that run or explicitly provide a VMR build ID.

We can't really unify how these two approaches work and automating checks for both of them is arguably too complicated for the benefit it provides. While the `validation` PR runs might not catch differences in the other code path, `test` runs will always catch any issues in this logic.

Additionally, the way we fetch pipeline builds is straight-forward enough that even if we do fail on incorrect tag or something similar the fix is relatively trivial (as seen from the PR in the issue description).

**Comment by oleksandr-didyk** [comment]
A separate issue might be to take a look at the lag of `validation` PR runs - they are using previous release as the basis. But I'm not really sure what we could do here besides allowing to skip `Stage-DotNet` completely and just try to release off any `installer` commit.

**Comment by oleksandr-didyk** [comment]
Discussed with Michael:
  - the original issue of not checking the two flows should be addressed by https://github.com/dotnet/source-build/issues/3297, as this would move the logic responsible for fetching the build into code which then can be covered by tests.
  - the secondary issue where we are not running against latest changes causing to brakes in `test` pipeline right before release is something more high-level and should be handled separately
