### ISSUE TITLE
Investigate fsharp bootstrapping build

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4185]
The fsharp repo has a [bootstrapping process](https://github.com/dotnet/dotnet/blob/e95411d8406bd0c077718d43df48abae7fb8c337/src/fsharp/eng/SourceBuild.props#L26) that contributes a fair amount to the overall build time of the repo. The bootstrapping is also problematic as described in https://github.com/dotnet/source-build/issues/4184. We should investigate what goes on as part of this bootstrapping and see if there's an alternative solution that doesn't require a build. Can we potentially make use of the previously source build artifacts instead?

**Comment by MichaelSimons** [comment]
I discussed this with @KevinRansom.  The bootstrap process is using the n-1 compiler to build the latest compile which is then in turn used to build the fsharp "product".  The bootstrap is necessary because FSharp makes use of new compiler features right away.  Using the n-1 compiler would not work because of this.
