### ISSUE TITLE
MergeAssetManifests task doesn't work correctly

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4263]
he produced merged manifest has the wrong VMR build number right now: `"`.

See https://github.com/dotnet/installer/blob/58e4c4f2e4fc66597ebf4ff54809dc88f286e217/src/SourceBuild/content/build.proj#L42 & https://github.com/dotnet/installer/blob/58e4c4f2e4fc66597ebf4ff54809dc88f286e217/src/SourceBuild/content/Directory.Build.props#L221

The `VmrBuildNumber` property has a typo in it, the trailing `"`. If I remove that, then I get errors that `VmrBuildNumber` isn't set. This makes me assume that `BUILD_BUILDNUMBER` isn't set.

@dkurepa

**Comment by dkurepa** [comment]
Yeah this is weird. It should be set according to the [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#:~:text=In%20YAML%20pipelines%2C%20you%20can%20reference%20predefined%20variables%20as%20environment%20variables.%20For%20example%2C%20the%20variable%20Build.ArtifactStagingDirectory%20becomes%20the%20variable%20BUILD_ARTIFACTSTAGINGDIRECTORY.). Might be safer to pass it as a parameter through yaml. I was going to do that for the `VerticalName` anyway, since we need this information to know which artifact to download

**Comment by akoeplinger** [comment]
hm weird, I looked at the console log and BUILD_BUILDNUMBER is in the list of environment variables we print before each repo build.

**Comment by dkurepa** [comment]
yeah, this variable is used by the `Publish.proj` when creating the AssetManifests, and we change set it before every repo build to match the BuildNumber in BAR for that commit. However, it should also be available before we start changing it

**Comment by ViktorHofer** [comment]
Looking at the binlog I see that it is manually set as an env var by us in the inner repo builds but it isn't available in Build.proj where we need it.

This task should work when doing a non-official build as well, therefore we need a different value than OfficialBuildId.

Could we use `_BuildNumber` which is set by Arcade? https://github.com/dotnet/arcade/blob/b6fada3ec4fa37e08dcbafaa6ddf59213f3f8687/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L47

For that you would need to set `DotNetUseShippingVersions` in Build.proj.

**Comment by ViktorHofer** [comment]
cc @mmitche

**Comment by dkurepa** [comment]
> Looking at the binlog I see that it is manually set as an env var by us in the inner repo builds but it isn't available in Build.proj where we need it.
> 
> This task should work when doing a non-official build as well, therefore we need a different value than OfficialBuildId.
> 
> Could we use `_BuildNumber` which is set by Arcade? https://github.com/dotnet/arcade/blob/b6fada3ec4fa37e08dcbafaa6ddf59213f3f8687/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L47
> 
> For that you would need to set `DotNetUseShippingVersions` in Build.proj.

wouldn't this cause the VmrBuildNumber to be the same for all builds in the same day? 

If we decided to pass the `Build.BuildNumber` as a parameter, then we could also put something there when doing non official builds

**Comment by ViktorHofer** [comment]
> wouldn't this cause the VmrBuildNumber to be the same for all builds in the same day?

That's already the current state when doing a dev or ci build. You will get package versions like `9.0.0-dev` or `9.0.0-ci`. Thinking more about this, I think what we actually want to set here is just `Version` which respects the OfficialBuildId in official builds.

**Comment by mmitche** [comment]
In the repos, it's passed in via OfficialBuildID. I think we should continue that pattern here.

**Comment by dkurepa** [comment]
In my dev branch I'm currently doing this:
- Passing the `OfficialBuildID` as a parameter for MSBUILD
- If it's not passed setting it to something in base Directory.Build.props
- When doing repo-proj builds, removing it with `RemoveProperties`, since the repo builds want to change it, but are not able to since it's a global property

**Comment by mmitche** [comment]
When not doing an official build (and not using a switch that emulates it), the build number isn't set. Instead the build revision and other info derived from the build number end up as constants.

https://github.com/dotnet/arcade/blob/b6fada3ec4fa37e08dcbafaa6ddf59213f3f8687/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L46-L47

**Comment by ViktorHofer** [comment]
Ok. But that sounds like the OfficialBuildId property itself isn't the correct input to the task as it isn't set outside of an official build. Or am I'm missing something?

**Comment by mmitche** [comment]
I think most likely, people aren't generating manifests outside of official builds. In arcade right now, it only happens when you pass -publish and /p:DotNetPublishUsingPipelines=true

https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L76

It does, however, look like BUILD_BUILDNUMBER is used: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L207

**Comment by mmitche** [comment]
I'm not quite sure why they chose to use that instead of BUILD_BUILDNUMBER to be honest.

**Comment by mmitche** [comment]
Oh, this is much sillier. @dkurepa @ViktorHofer The issue is that this repo uses explicit docker commands to run its Linux builds. The ambient environment isn't passed through implicitly.

Check the Windows manifest. it has a correct build number (with a quote)

**Comment by ViktorHofer** [comment]
> I think most likely, people aren't generating manifests outside of official builds. In arcade right now, it only happens when you pass -publish and /p:DotNetPublishUsingPipelines=true

Right. Repos do use the `-sign -publish` switches on CI because Arcade's cibuild.cmd/sh appends those but `DotNetPublishUsingPipelines` only gets set to true when doing an official build.

Now inside the VMR, the inner repos do publish and set `DotNetPublishUsingPipelines` to true copy the files to disk. An example from command-line-api public CI build:

![image](https://github.com/dotnet/source-build/assets/7412651/3e3ee6a1-dd5a-42fc-91de-db0849594c8e)

When we start treating everything as an official build, [we won't pass `OfficialBuildId` in anymore](https://github.com/dotnet/installer/blob/320d6542c5df97b1bc30239c9de2279e86fb2a94/src/SourceBuild/content/repo-projects/Directory.Build.props#L144C56-L144C71). What would the value then be?

**Comment by ViktorHofer** [comment]
If that metadata doesn't matter unless we actually publish to AzDO / BAR then using OfficialBuildId sounds right. That would then just be empty in non-official builds.

**Comment by mmitche** [comment]
To summarize:
- I want to go back on my statement that OfficialBuildId should be used for the outer manifest invocation. It looks like we use BUILD_BUILDNUMBER in arcade to generate the manifest. OfficialBuildId is used to generate package versions. While we could use OfficialBuildId in place of BUILD_BUILDNUMBER, there are other properties that are AzDO specific so keeping it consistent is better IMO.
- The actual metadata does not matter except when publishing to BAR, so empty strings and all that are fine in local builds
- BUILD_BUILDNUMBER is unset (along with other AzDO properties) because the env vars aren't explicitly fed into the docker commands.

**Comment by ViktorHofer** [comment]
[This task parameter needs an update](https://github.com/dotnet/installer/blob/ba50c92ce566e2c5f13597dded207714ce6f38d7/src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/MergeAssetManifests.cs#L31-L35) to allow an empty string. Please also update the xml doc above with some of this information:

> The actual metadata does not matter except when publishing to BAR, so empty strings and all that are fine in local builds

Please also add a comment in the target where you pass the `BUILD_BUILDNUMBER` in and mention that it's fine if this value is empty.

**Comment by ViktorHofer** [comment]
This got fixed by https://github.com/dotnet/installer/pull/19217
