### ISSUE TITLE
VMR smoke test project hardcodes package versions and TFM

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4289]
See https://github.com/dotnet/installer/blob/d28a790713cc31b2293715bd075814df5b5f78de/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj#L11-L14

Having these hardcodes increases the chance of CG warnings. In addition, the hardcoded xunit version means that this test project won't use the latest xunit as the rest of the stack.

Now that we have another [test project in the VMR orchestrator](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/Microsoft.DotNet.UnifiedBuild.Tests.csproj) which fully uses the VMR infrastructure, it might make sense to change smoke tests to use the repo infrastructure as well. Currently this isn't happening because of this file: https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/Directory.Build.props

@ellahathaway @MichaelSimons

Let me know if that sounds right to you as I would be happy to submit a PR to make that happen and as part of that also clean-up how the smoke test project is invoked so that is in more in line with the other test project.

**Comment by ViktorHofer** [comment]
Here's a draft PR that shows the changes that I had in mind: https://github.com/dotnet/installer/pull/19290

**Comment by ellahathaway** [comment]
I agree that those hardcoded versions need to be removed. However, it looks like [this file](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/Directory.Build.props) was added to support the test infra building independently of the VMR? If that's the case, I want to ensure that these changes will still allow us to run the smoke tests without having to do a full build of the VMR. I often run the smoke tests locally, and it'd be a pain to have to depend on a build of the VMR in order to run them.

**Comment by ViktorHofer** [comment]
Yes, using the repo infrastructure won't mean that the VMR needs to be built. With my draft PR, running the smoke tests will be easier actually.

**Comment by ellahathaway** [comment]
Sounds good! I just wanted to clarify since your PR says "This allows the test project to just be invoked with dotnet test or dotnet build /t:Test after the VMR is built." I'm good with these changes as long as the VMR does not need to be built. Thanks, Viktor.

**Comment by mthalman** [comment]
In general, I'm on board with these proposed changes. It provides better alignment and better structure of the tests.
