### ISSUE TITLE
SDK Diff Tests failing with `Didn't find an SDK archive`

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4420]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2458671&view=logs&j=c2a3fba4-babc-5882-e82a-8e0dc9edd6ec&t=c2a95e7e-b619-54b2-c512-fcefc49a38ba&l=17):

`/mnt/vss/_work/1/s/Directory.Build.targets(15,5): error : Didn't find an SDK archive. [/mnt/vss/_work/1/s/eng/extract-sdk-archive.proj]Didn't find an SDK archive`

This is likely a regression from https://github.com/dotnet/sdk/pull/40983

Link to code change: https://github.com/dotnet/sdk/blame/38e537cdf1cf95c74cd4970862b483dc9b0f774b/src/SourceBuild/content/Directory.Build.targets#L11

**Comment by MichaelSimons** [comment]
Given the error, it leads me to think this is an issue trying to extract the source-build SDK, not the microsoft built SDK.  The VMR's test infrastructure has support for extracting the VMR built SDK [here](https://github.com/dotnet/dotnet/blob/main/eng/extract-sdk-archive.proj).  This is where the exception message is coming from.  Try running the tests locally.  This logic is new and may have changed since the SDK diff tests last ran.

**Comment by ellahathaway** [comment]
Looking through the binlogs, you're right that it calls the logic in extract-sdk-archive.proj. This project file depends on the `DetermineSourceBuiltSdkVersion`, which is where the error occurs. It thinks that the SDKTarballItem is at `vmr/artifacts/assets/Release/Sdk` and then errors when it can't find the SDK there.

**Comment by Winniexu01** [comment]
Reopen this issue because `License scan tests` failed with the same issue but [this](https://github.com/dotnet/sdk/pull/41124) cannot fix it. The license scan test code does not contains the parameter `SdkTarballPath`.

**Comment by ellahathaway** [comment]
@Winniexu01 - The license scan tests have been succeeding and running without encountering this error. Can you point to a build where this is occurring?
