### ISSUE TITLE
Cleanup `release/9.0.1xx-teststablep5` Branches

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4469]
As part of the work to get a coherent build for the release post the installer -> sdk merge, a branch titled `release/9.0.1xx-teststablep5` was created in sdk and dotnet. The existence of this branch is causing the source-build-license-scan pipeline to be triggered to run on the branch every Monday. This wastes compute, so, seeing as this branch is no longer in use, we should remove the branch both internally and publicly.

**Comment by mthalman** [comment]
This was a temporary branch but there are also other older preview branches that are causing the license scan pipeline to run: [release/9.0.1xx-preview4](https://dev.azure.com/dnceng/internal/_build/results?buildId=2475228) and [release/9.0.1xx-preview5](https://dev.azure.com/dnceng/internal/_build/results?buildId=2475226&view=results) (internal links). These continue to run because there has not been a successful build of the license scan for those branches. But those branches will not have any new changes.

We have 3 options:
* Update the YAML to explicitly exclude these branches
* Override the triggers in the AzDO UI. But that doesn't support wildcards so you need to add it for each branch now and in the future.
* Delete the branches

Deleting the branches would be preferable. @mmitche - Can we do that for the VMR since we have release tags? If so, we should probably apply that to 8.0 as since there are still 8.0 preview branches. And also make this part of the regular release workflow.

**Comment by mmitche** [comment]
Yeah I'm fine with deleting from the VMR

**Comment by mthalman** [comment]
Closing as the branch has been deleted.
