### ISSUE TITLE
Reduce Developer Time Spent on Investigating Smoke Test Failures

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4517]
We've made some improvements to the time we're spending on getting green sdk-diff-test pipeline runs, but we are still spending a good amount of time investigating the diffs when changes occur. As a result, I've compiled a list of the two types of test that tend to cause us the most investigation time and some ideas for lowering dev investigation time:

### Artifact Size Test
- Goal: Catch large changes to the artifacts.
- Current Implementation: Check every artifact and fail if the size change is > 25%.
- Problems:
  - Artifacts change frequently, often due to known product changes
  - Has not caught any large changes to artifact sizes
- Past Strategies for Lowering Dev Overhead:
  - Automating the process of updating the baseline by opening PRs for diffs
  - Only updating the baseline for artifacts with size diffs over the percentage threshold
- New Ideas for Lowering Dev Overhead:
  - Check larger packages (e.g., entire .packs/ instead of individual items in packs/).
  - Push test onto product repositories (https://github.com/dotnet/source-build/issues/4475)
  - Implement dynamic size allocations (different size thresholds based on the importance, usage, and frequency of changes).
  - Integrate with version control to get a list of commits relevant to the artifacts being changed

### SDK Diff Tests
- Goal: Catch differences between the Microsoft SDK and the source build SDK.
- Current Implementation: List content and diff. Fail if there are any unknown differences
- Problems:
  - Differences can be time-consuming to investigate.
  - Hard to determine which differences matter and which don't.
  - No clear definition on what to exclude and what to add to baselines.
- Past Strategies for Lowering Dev Overhead:
  - Automating the process of updating the baseline by opening PRs for diffs
  - Detecting unused exclusions and removing them from the exclusions lists
- New Ideas for Lowering Dev Overhead:
  - Use git version history (include a GitHub compare link for differences between the commit from the last successful run and the current failing run)

**Comment by mthalman** [comment]
As explained in https://github.com/dotnet/source-build/issues/4475, my preference is that the artifact size tests be pushed to the product teams.

For the SDK diff tests, perhaps we need a more intelligent comparison. The goal is that a diff will indicate that something needs to be addressed, not ignored/excluded. So I think we need to get a better understanding of the types of diffs that have occurred. For those diffs which are acceptable, we should classify those, we obviously want those diffs to be excluded from the result. The problem is that the exclusion is solely based on string matching. We may need the algorithm to better understand the semantics of the components making up the SDK. For example, rather than simply excluding all of dotnet-watch, maybe it should only exclude dependencies of dotnet-watch that come from MSBuild. So this would not be a string matching algorithm but rather it would have an understanding of the dependency graph and can dynamically exclude content based on that. This is just one example. The point is that we need to have a better understanding of the types of diffs that have occurred and from there we can figure out how best to exclude them.

The idea of using git commits to track content differences is interesting. I worry that it would be complex to implement and may have maintenance cost associated with it (which is what we're trying to avoid with all of this).

**Comment by MichaelSimons** [comment]
[Triage] @ellahathaway, Let's break this issue apart as the actions are separate and will be done on different timelines.

**Comment by ellahathaway** [comment]
Closing in favor of https://github.com/dotnet/source-build/issues/4528 and https://github.com/dotnet/source-build/issues/4529
