### ISSUE TITLE
Malware scan execution error in VMR

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4526]
The `1ES PT: AntiMalware ClamD Linux Scanner (Binary)` step from the 1ES templates shows `Pass` but with the following error in [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2502201&view=logs&j=b9abe003-a5da-5729-0444-865506f15e35&t=0847025d-ce9a-5267-a9d5-00b5b4cc9782&l=1107):

    ----------- SCAN SUMMARY -----------
    Infected files: 0
    Time: 0.000 sec (0 m 0 s)
    Start Date: 2024:07:25 10:33:56
    End Date:   2024:07:25 10:33:56
    ERROR: Could not connect to clamd on LocalSocket /var/run/clamav/clamd.ctl: No such file or directory
    ##[error]1ES PT Warning: Malware scan execution error in '/mnt/vss/_work/1/a/BuildLogs' with exit code '2'. This could be because the 'freshclam' could not update the virus databases.

**Comment by MichaelSimons** [comment]
From an internal discussion with the 1ES folks.

"This is a known issue. Unfortunately we cannot influence clamd behavior as it is a third party tool. Because of the amount of requests to clamd database it gets throttled. We are actively working on replacing it with Defender for Linux."

Given this isn't actually failing our builds I am going to close this issue as there is no action for us to take.
