### ISSUE TITLE
SBE failing due to use of preview version of .NET

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4527]
[This PR build](https://github.com/dotnet/sdk/pull/42359) targeting preview7 failed with the following error while building source build externals:

```
/vmr/.dotnet/sdk/9.0.100-preview.7.24357.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(326,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/vmr/src/source-build-externals/artifacts/sb/src/src/spectre-console/src/Spectre.Console/Spectre.Console.csproj::TargetFramework=net9.0]
      /vmr/.dotnet/sdk/9.0.100-preview.7.24357.2/Roslyn/Microsoft.CSharp.Core.targets(89,5): error MSB6006: "csc.dll" exited with code 139. [/vmr/src/source-build-externals/artifacts/sb/src/src/spectre-console/src/Spectre.Console/Spectre.Console.csproj::TargetFramework=net9.0]
```

**Comment by ellahathaway** [comment]
https://github.com/dotnet/dotnet/blob/76d842118ea686c6d31a842a392d53a4680b2f91/Directory.Build.props#L125 is set, investigating why it didn't propagate/maybe got overridden.

**Comment by ellahathaway** [comment]
I retried this build and it passed. Based on the error message, the build should have failed.

I also looked through the SBE binlog, and `SuppressNETCoreSdkPreviewMessage` is set to true for the specre-console project. This leads me to believe that the error is not actually related to us using a preview version of .NET. It's possible that this was caused by a race condition of sorts or an issue with the build agents.

@MichaelSimons - do you have any thoughts on this?

**Comment by MichaelSimons** [comment]
I don't think the build failure was caused by the preview SDK usage and the passing retry support this.  Look at the inner [binlog](https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzc1NDczOS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOV9PbmxpbmVfTXNmdFNka194NjRfQnVpbGRMb2dzX0F0dGVtcHQx0/content?format=file&subPath=%2Fsrc%2Fsource-build-externals%2Fartifacts%2Fsb%2Fsrc%2Fsrc%2Fspectre-console%2Fbuild.binlog) for  the spectre.console project that failed.  It has the following failure reported - _CompilerServer: server failed - server rejected the request 'Compilation not allowed at this time' - Spectre.Console (net9.0)_

**Comment by ellahathaway** [comment]
> I don't think the build failure was caused by the preview SDK usage and the passing retry support this. Look at the inner [binlog](https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzc1NDczOS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOV9PbmxpbmVfTXNmdFNka194NjRfQnVpbGRMb2dzX0F0dGVtcHQx0/content?format=file&subPath=%2Fsrc%2Fsource-build-externals%2Fartifacts%2Fsb%2Fsrc%2Fsrc%2Fspectre-console%2Fbuild.binlog) for the spectre.console project that failed. It has the following failure reported - _CompilerServer: server failed - server rejected the request 'Compilation not allowed at this time' - Spectre.Console (net9.0)_

Ah thanks! I missed that inner binlog. It looks like an issue with the tooling then.

cc @dotnet/roslyn

**Comment by jaredpar** [comment]
I suspect this is another manifestation of https://github.com/dotnet/dnceng/issues/3305

There are two interesting parts in the binlog. 

> CompilerServer: server failed - server rejected the request 'Compilation not allowed at this time' - Spectre.Console (net9.0)

That message is given when a compilation request occurs while the compiler server is shutting down. That is not necessarily an error. The server could be timing out from lack of requests when this happens. Typically though when I see this I grep the binlog for `$message Compiler Server:` and see if there is an earlier compilation that had a real error that brought down the server. In this case there is only csc call so that is not the case. Most likely a graceful shutdown race from an earilier build on same machine. 

> /vmr/.dotnet/sdk/9.0.100-preview.7.24357.2/Roslyn/Microsoft.CSharp.Core.targets(89,5): error MSB6006: "csc.dll" exited with code 139. [/vmr/src/source-build-externals/artifacts/sb/src/src/spectre-console/src/Spectre.Console/Spectre.Console.csproj]

That is just a straight up compiler crash. Once the server rejected the request it fell back to direct invoke of csc.dll and that crashed. Unfortunately Linux doesn't always put a call stack in the build file so we can't see what is happening. But given that one manifestation of [dnceng 3305](https://github.com/dotnet/dnceng/issues/3305) is a straight crash we should likely wait for that investigation to resolve.

**Comment by ellahathaway** [comment]
@jaredpar - Thanks for the in depth explanation! It sounds like this is likely caused by https://github.com/dotnet/dnceng/issues/3305, so I'm going to close this issue in favor of https://github.com/dotnet/dnceng/issues/3305.

**Comment by jaredpar** [comment]
Note: may also be https://github.com/dotnet/runtime/issues/104123

There are two investigations on going right now which have this symptom.
