### ISSUE TITLE
[Release pipeline] Exclude wiki link to smoke test prereqs tarball for .NET 9

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4714]
For a .NET 9 release, the wiki page that gets generated for partners includes a link to the feed to download the smoke test prereqs tarball. But we don't publish this tarball for .NET 9. It's only for .NET 8 and earlier. A link to the feed location should be excluded from the generated wiki page.

**Comment by ellahathaway** [comment]
@mthalman - This was already addressed in [this PR](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39599). Looking at the wiki content that got published, the prereqs tarball was not included: https://dev.azure.com/dotnet-security-partners/dotnet/_wiki/wikis/dotnet.wiki?wikiVersion=GBwikiMaster&pagePath=/Release%20Info/2024/9.0.100%20November%202024&_a=compare&version=1267fda71af153a0f3e30e808cb9a1702690f0d5&view=preview.

That said, I think [the template](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/eng/pipeline/source-build-release/message-templates/version-template.md) can be revised though so that the artifact feed and tarball (when included) are their own major bullets rather than being sub-bullets under `<sdk_version> smoke test prereqs`.

**Comment by ellahathaway** [comment]
Opened https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/45280

**Comment by mthalman** [comment]
You're right. I don't know what I was seeing that caused me to create this issue. However, based on discussion with partners, it sounded like we didn't need to provide the tarball for 8.0 anymore either.
