### ISSUE TITLE
CreateRpmPackage is passed a non-portable RID for PackageOS in source-only builds

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/source-build#4728]
In https://github.com/dotnet/sdk/pull/44751 we saw that the sdk-source-build job fails because we're passing the non-portable RID into the CreateRpmPackage task. We added a temporary workaround to override `InstallerRuntimeIdentifier`, this issue tracks removing that.

<img width="1404" alt="image" src="https://github.com/user-attachments/assets/0868a870-fa3b-47dc-b030-ebe9f1702182">

**Comment by tmds** [comment]
@ViktorHofer @jkoritzinsky I saw some PRs go by which peeked my interest.

> In https://github.com/dotnet/sdk/pull/44751 we saw that the sdk-source-build job fails because we're passing the non-portable RID into the CreateRpmPackage task.

For my understanding: this issue popped up because you've started doing a non-portable build that produces RPM packages?

Until now `BaseOS` has been a property local to the runtime repo that was used only in updating the rid graph. If it is going to serve a broader role, perhaps it should be (renamed? and) included in https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/Unified-Build-Controls.md?

Runtime has its own logic to figure out what the portable target OS is: https://github.com/dotnet/runtime/blob/ab7e12334f07b72e67b897e9ae7a09d04fd1efb5/Directory.Build.props#L200-L201. If `BaseOS` gets passed round, we should probably use it there.

**Comment by jkoritzinsky** [comment]
We've started building our rpms by default in all scenarios, including source build. The non-portable source-build jobs caught this issue.

**Comment by MichaelSimons** [comment]
> We've started building our rpms by default in all scenarios, including source build. The non-portable source-build jobs caught this issue.

We should not be producing packages in source-build scenarios.

**Comment by jkoritzinsky** [comment]
We can disable the package production in source build. I was initially going to do that, but the projects were explicitly opted-in for source build (under a `DotNetBuildFromSource=true` condition).

**Comment by MichaelSimons** [comment]
> We can disable the package production in source build. I was initially going to do that, but the projects were explicitly opted-in for source build (under a `DotNetBuildFromSource=true` condition).

That seems preferrable.  Distro maintainers are responsible for their own package creation.

**Comment by tmds** [comment]
@jkoritzinsky will you be reverting the PRs that use `BaseOS`? If not, then it would be good to do the work to include it in https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/Unified-Build-Controls.md#output-controls (perhaps with an updated name). Before we had these clear definitions, fussiness around the meaning of Rids/OSes has been a source of confusion and bugs.

**Comment by jkoritzinsky** [comment]
I don't think I'll revert the PRs, so I'll update the controls doc when I have some time.
