### ISSUE TITLE
Improve native bootstrapping

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#576]

**Comment by deinok** [comment]
Hi, the folder that outputs the release should be mkdired. In cas of inexistence of for example "rhel.6-x64/dotnetcli" create it and continue the execution

**Comment by omajid** [comment]
The general native bootstrap scripts (https://github.com/dotnet/source-build/blob/master/scripts/bootstrap/buildbootstrapcli.sh) was added by https://github.com/dotnet/source-build/pull/274. 

> the folder that outputs the release should be mkdired.

This was fixed by https://github.com/dotnet/source-build/pull/675.

Is there anything that still remains to be done?
