### ISSUE TITLE
Don't invoke MSBuild from within the CLI

### ISSUE THREAD

**Issue by ellismg** [dotnet/source-build#58]
Today, we invoke `MSBuild.dll` directly from within the CLI.  We do this (vs `dotnet msbuild`) because `dotnet msbuild` pushes some [additional stuff into your environment](https://github.com/dotnet/cli/blob/85ca206d84633d658d7363894c4ea9d59e515c1a/src/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs#L29).  This causes downstream issues in repositories that don't expect these things to be set to the values CLI uses, since they use different build toolsets.

@piotrpMSFT and @eerhardt have asked that we don't do this, as they want the freedom to move stuff within the CLI around and don't want to be a general purpose MSBuild distribution mechanism.  Their concern is if folks see another "dotnet" project doing this they will think it's a good and right thing to do.

So instead, we need to start restoring and publish MSBuild, and then invoke that MSBuild.dll (we can do this after building our tasks but before jumping into build.proj.

**Comment by karajas** [comment]
@eerhardt do you know if this is still the case?

**Comment by eerhardt** [comment]
It is still the case that we don't want anyone being dependent on the internal folder layout of the .NET Core SDK.  So if you are still assuming that `MSBuild.dll` is in a specific location of the SDK, then it still needs to be changed.

**Comment by weshaggard** [comment]
@eerhardt I agree that we should try to use dotnet msbuild instead of assuming its location in the CLI and I also prefer that over downloading our own msbuild to use. What do you think is the right solution here? Should we fix the repos that don't work with this env variable or fix the CLI to stop setting them?

**Comment by jaredpar** [comment]
In general we need to be killing environment variables. Letting them influence our build this way is just creating a new razzle. Not our goal. 

Instead use explicit parameters

**Comment by eerhardt** [comment]
> What do you think is the right solution here? 

I think the right solution is what I said on Mar 7.  https://github.com/dotnet/source-build/issues/58#issuecomment-284881167

I think the CLI needs to change to allow for this scenario.

**Comment by weshaggard** [comment]
If that is the case it sounds like we need a CLI issue tracking this so we can make some progress. cc @livarcocc @nguerrera

**Comment by eerhardt** [comment]
That being said, I also think we need to fix certain repos - like corefx - that don't use the CLI's `dotnet` to build on Windows, but use it to build on Linux.  I think building corefx should be consistent across platforms.  Instead today it uses whatever MSBuild is on the path, which is different between machines, and different between command prompts on the same machine.

**Comment by weshaggard** [comment]
>That being said, I also think we need to fix certain repos - like corefx - that don't use the CLI's dotnet to build on Windows, but use it to build on Linux. I think building corefx should be consistent across platforms. 

Totally agree that is something that is being worked on by @joperezr

**Comment by nguerrera** [comment]
I would like to understand why it's a requirement to let any constituent repos of source build override the compiler that is used. Ultimately, everything should be building with the same LKG toolset.

**Comment by eerhardt** [comment]
Because as it currently exists, different repos use different toolsets.

For example, coreclr and corefx use BuildTools, which currently brings its own MSBuild, Roslyn, etc.  And on Windows, these repos currently use whatever MSBuild.exe is on the $Path, so there's another toolset.

The cli repo uses a different toolset to build - it uses a previously build .NET Core SDK which has a different MSBuild, Roslyn, etc.

I agree we should be moving towards using the same toolset, but it is taking a long time to get there.  And to me it doesn't look like it is happening any time soon.

Another reason is because there are varying needs between the repos, and the same toolset may not work for all repos at all times.  For example, right now corefx is using C# 7.2 and the latest Roslyn compiler.  However, the latest Roslyn compiler is breaking coreclr.  See https://github.com/dotnet/coreclr/pull/14002#issuecomment-331005573.  So in this case, we would be blocking corefx from moving forward because coreclr can't take the updated compiler.

**Comment by nguerrera** [comment]
Thanks for the explanation. In the longer term, I imagine the one lkg toolset to be recent and updated frequently. And updates to the toolset could be gated on a successful full stack build.

Just as we coordinate product dependencies across the stack, we should coordinate build dependencies.

Regardless, I don't disagree about fixing those hacked env vars and we can of course start there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nguerrera** [comment]
https://github.com/dotnet/cli/pull/7311 by @khyperia will remove the setting of CscToolExe. :) It is going in to 15.5 SDK. I think we wait until source build can use a 15.5+ SDK as LKG and then switch source-build to plain `dotnet msbuild`. I'm not worried about `dotnet path/to/msbuild.dll` in the meantime because 2.0 SDK layout won't ever change.

**Comment by livarcocc** [comment]
We just took a PR in master from @khyperia where we are no longer setting `CscToolExe`.

**Comment by crummel** [comment]
Applies to `build.ps1`, `build.sh`, and `support/tarball/build.sh`.
