### ISSUE TITLE
2.1.301 and 2.1.401 have incorrect NETStandardPackageVersion

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#769]
The source-build sdks have an incorrect version for NETStandardPackageVersion:
```
./sdk/2.1.302/Microsoft.NETCoreSdk.BundledVersions.props:    <BundledNETStandardPackageVersion>2.0.2-servicing-25519-03</BundledNETStandardPackageVersion>
./sdk/2.1.401/Microsoft.NETCoreSdk.BundledVersions.props:    <BundledNETStandardPackageVersion>2.0.2-servicing-25519-03</BundledNETStandardPackageVersion>
```
This version is used for `NETStandard.Library` and causes restores to fail when setting `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`.

Steps to Reproduce:

1. Create a library project using `dotnet new classlib`
2. Add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` to the csproj PropertyGroup section
3. run dotnet restore

**Comment by dagood** [comment]
Confirmed: I saw this when working on 2.1.402 and have a fix in https://github.com/dotnet/source-build/pull/767, https://github.com/dotnet/source-build/pull/767/commits/538293be4d495fd260b01e2bb7f6cf1694209c0f.

This is related to the problems discussed in https://github.com/dotnet/source-build/issues/748, where the Microsoft official build/ProdCon doesn't consistently build everything, so Source-Build doesn't currently have reliable auto-update. (Some potential new automated checks discussed in the issue.)

**Comment by omajid** [comment]
I can confirm that I can reproduce this with 2.1.401 but not with 2.1.402 builds.

**Comment by tmds** [comment]
That will fix the 2.1.4xx sdk package. @omajid we may want to fix this difference for the 2.1.3xx package too? @dagood is it doable to patch the 2.1.3xx sdk in a similar way?

**Comment by dagood** [comment]
I think the same change on 2.1.3xx would work. Looking at the Core-Setup submodule at https://github.com/dotnet/source-build/tree/v2.1.301/src, it [also depends on NETStandard.Library 2.0.3](https://github.com/dotnet/core-setup/blob/6985b9f6844d51ba1197c3f52aabc7291bb15bc1/dependencies.props#L23). The complication I described in #767 was due to a conflicting change that isn't in v2.1.301.

**Comment by dagood** [comment]
Yeah, the source-build branching structure is tied to runtime versions so we don't (currently) have anywhere to publish that fix. (I'm not sure if the same patching strategy applies to Microsoft builds from dotnet/cli, since they do have a branch, at least.) I originally read @tmds' comment in the context of Red Hat making a patch, but yeah, unfortunate there's nowhere to put it in this repo right now.

@dseefeld do you know if this is going to change?

**Comment by tmds** [comment]
My question is about making source-build 2.1.302 sdk behave more like Microsoft 2.1.302 sdk.
It requires not a patch of the Microsoft 2.1.302, but of source-build 2.1.302.

It could be fixed in source-build. We could apply it as part of our build. Or we consider it a source-build 2.1.302 sdk known issue.

As long as source-build and Microsoft-build are potentially out-of-sync, it is interesting to have a way of fixing those differences if they are discovered later on.

**Comment by dseefeld** [comment]
The eventual goal is to split runtime and sdk for source-build.  That would help alleviate this issue, but the change is not going to happen anytime soon.
