### ISSUE TITLE
Generate symbol packages

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#783]
@Raviuppa (I hope I have the right github username) was asking me about managed debug information for the binaries source-build produces and it made me realize that source-build does not produce symbol packages (`*.symbol.nupkg`) in a way that can be published along with the cli built by source-build.

Is this something that can be easily fixed?

cc @davemulford

**Comment by omajid** [comment]
On the other hand, unmanaged (native) debug info seems like it is present in all binaries generated by source-build, so no issues there.

**Comment by dagood** [comment]
What would make them publishable along with the source-built CLI/SDK? We currently have a bunch of symbol packages in `bin/obj/x64/Release/blob-feed/assets`. (Not sure if every single project makes them, but the list looks substantial.) Copying them to something like `bin/x64/Release/symbols/`?

**Comment by omajid** [comment]
> What would make them publishable along with the source-built CLI/SDK? 

Sorry, I dont know enough about how tools expect to consume them. I am wondering if it would be enough to copy the `*.symbol.nupkg` files to some well-known location on disk. Perhaps then tools can find what they need. I am looking into this.

> Not sure if every single project makes them, but the list looks substantial.

That's my major concern. I see coreclr in there, but much of corefx is missing. For example:

```
$ find -iname '*coreclr*symbol*nupkg'                                                 
./dotnet-2.1.4/bin/obj/x64/Release/blob-feed/assets/Microsoft.NETCore.Runtime.CoreCLR.2.1.3.symbols.nupkg            
./dotnet-2.1.4/bin/obj/x64/Release/blob-feed/assets/runtime.fedora.28-x64.Microsoft.NETCore.Runtime.CoreCLR.2.1.3.symbols.nupkg
$ find -iname '*linq*symbol*nupkg'                                                    
$ find -iname '*nongeneric*symbol*nupkg'                                              
$ find -iname '*collect*symbol*nupkg'                                                 
$ find -iname '*socket*nupkg'
```
Am I looking for the wrong file names?

**Comment by dagood** [comment]
Most of CoreFX was consolidated into `runtime.*.Microsoft.Private.CoreFx.NETCoreApp`, which ships through `runtime.*.Microsoft.NETCore.App`. You can find stuff like `System.Linq.Parallel.pdb` and `System.Collections.Concurrent.pdb` through that package's symbol package.

What definitely is missing are symbols for DLLs that aren't packaged during every CoreFX build: stuff like `System.Data.SqlClient`. I expect https://github.com/dotnet/source-build/pull/653 and work like that to start closing that gap.

Symbol packages are just a delivery mechanism, so I wouldn't be surprised if you'd have to extract them all into a directory and arrange them to match how the lookup mechanism expects them. The Microsoft build symbol consumption scenario relies heavily on the idea of symbol servers and on-demand lookup, and this is all I'm familiar with, unfortunately.

@mikem8361 is there a better approach to this scenario you're aware of?

**Comment by omajid** [comment]
Ahh! That's great. I can see this on my builds too:

    $ unzip -l ./dotnet-2.1.4/bin/obj/x64/Release/blob-feed/assets/runtime.fedora.28-x64.Microsoft.Private.CoreFx.NETCoreApp.4.5.0-servicing-26814-02.symbols.nupkg | grep pdb | wc -l
    135

So I guess other than the strange version of this package, I just need to extract things to the right locations, or figure out how the tools discover these symbols.nupkg file.

**Comment by dagood** [comment]
@omajid I suggest using just `runtime.*.Microsoft.NETCore.App`: it groups together CoreCLR and CoreFX, and has stabilized versioning. (The `Private` package from CoreFX is always built unstable because they are never published to the NuGet Gallery, and their Major.Minor.Patch is on a different version train.)

@mikem8361 the symbol downloader requires a symbol server to work, though, right? For context, this is source-build, where the assets aren't built by Microsoft and don't go to symbol servers.

That reminds me, though, about https://github.com/dotnet/symstore/tree/master/src/NugetSymbolServer. In theory you could run this on a set of symbol packages locally, then download symbols from that, right? That doesn't sound like a great way to actually embed in the product, but seems like what we have now....

**Comment by mikem8361** [comment]
That symbol server would probably work, but it was something just hacked up for testing.  It may need some a little work to be usable.

**Comment by omajid** [comment]
@dagood Thanks for the pointers. I feel like we need to do something to tell all the consumers of source-build about which symbols.nupkg files should be made available (on disk, symbols server, etc) and which should not be.

**Comment by dagood** [comment]
@dseefeld I think we need an issue tracking this in https://github.com/dotnet/source-build/issues/751 "Build Fedora packages from source-build that meets packaging guidelines".

I found these describing symbols are expected to be packaged for more info (followed links from the main docs we have linked in the readme):
* https://fedoraproject.org/wiki/Packaging:Debuginfo
* https://www.debian.org/doc/manuals/maint-guide/advanced.en.html

**Comment by omajid** [comment]
As far as I understand, dealing with unmanaged (native) symbols is quite easy. All we need to do is compile with `-g` and not strip binaries (executibles and shared libraries) after they are built. At least on Fedora, the rpm build system takes care of the rest. This is already true for source-build. I don't know if anything else needs to be done for unmanaged symbols.

On the other hand, I dont know what to do about managed symbols. I am not sure which files need to be shipped and how.

**Comment by dagood** [comment]
Agreed, to be clear, I was linking those as a reference for how symbols in general are normally packaged up, to hopefully help find how to make managed symbols work in a similar way.

The other angle is determining what is acceptable for a distro package:

1. Require the package maintainer to host a symbol server?
2. Require the developer/user to stand up their own machine-local symbol server to access symbols? (Or stand up one for their (firewalled?) organization to share?)
   * Better for offline experience--the `.symbol.nupkg` files would be already downloaded with the debuginfo package, I imagine.
3. Ship a debuginfo package that includes the managed symbols, and the SOS lldb plugin knows where to find them by default?

To me (with no experience debugging a distro package, only some reading) the first two seem unusual. For for the third, I don't know how managed symbols are discovered when trying to debug them. I see https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-core-dumps-with-lldb, but I'm not sure how PDBs are discovered.

@omajid, what do you think about those approaches?

@mikem8361, do you know more about the managed PDB loading?

**Comment by mikem8361** [comment]
SOS under lldb currently only loads managed PDBs next to their assembly.  There isn’t even a settable search path (yet).  I do have a work item to add symbol server support (which won’t help here) to SOS/lldb and could add some else too if it is simple (like a search path).  Currently, the recommended way to get PDBs is to use the “dotnet-symbol” tool on Linux to download them (and put them side-by-side with the assemblies).

**Comment by dagood** [comment]
Hmm, that makes me rethink something... I've been assuming the symbols have to install to a different location, but I don't know any reason PDBs couldn't be installed into the SDK's `shared/Microsoft.NETCore.App/{version}/` directory alongside the DLLs.

Also, I've been talking about the runtime symbol package, but there is another artifact `bin/obj/x64/Release/blob-feed/assets/dotnet-runtime-symbols-2.1.4-{RID}.tar.gz` that has the runtime's managed symbol files flat in the root. Maybe it's as simple as extracting that into `.../shared/Microsoft.NETCore.App/{version}/` for the debuginfo package? (We could start copying it somewhere in `bin/x64/Release` to indicate it's relevant, if that works.)

Something similar could be done for the `.../sdk/{version}/` dir too, I'd think, for debugging managed SDK tooling.

---

Another approach I thought of is making `dotnet-symbol` able to search a directory of symbol packages, rather than only talk to symbol servers. Then the symbol packages could simply be placed on the system and `dotnet-symbol` pointed to it. Then everyone could use that recommended flow.

(If we do that, we should make sure `dotnet-symbol` can build from source.)

**Comment by mikem8361** [comment]
Maybe this doesn't apply here but you need to be supervisor to write the symbol files side-by-side with the assemblies if the runtime is installed in /usr/share/dotnet/shared/Microsoft.NETCore/{version}. 

dotnet-symbol defaults to side-by-side installation but the symbol files would need to be download in a tmp dir and copied to the above dir.

It would be simple to add directory or share support to dotnet-symbol.  It is already uses RoslynTools.RepoToolsSet so it should be fairly easy to convert to Arcade and make it part of the source build.

**Comment by tmds** [comment]
Resurrecting this discussion.

> Also, I've been talking about the runtime symbol package, but there is another artifact bin/obj/x64/Release/blob-feed/assets/dotnet-runtime-symbols-2.1.4-{RID}.tar.gz that has the runtime's managed symbol files flat in the root. Maybe it's as simple as extracting that into .../shared/Microsoft.NETCore.App/{version}/ for the debuginfo package? (We could start copying it somewhere in bin/x64/Release to indicate it's relevant, if that works.)

@dagood does this still apply? That sounds like something we can make work.
@omajid wdyt?

> Maybe this doesn't apply here but you need to be supervisor to write the symbol files side-by-side with the assemblies if the runtime is installed in /usr/share/dotnet/shared/Microsoft.NETCore/{version}.

That is an ok limitation. On Linux system, installing debug symbols requires root typically.

> dotnet-symbol defaults to side-by-side installation but the symbol files would need to be download in a tmp dir and copied to the above dir.

Symbols should come via the OS package manager (like other debuginfo).

**Comment by dagood** [comment]
Yep. So, the whole plan, without `dotnet-symbol`:

* For native symbols, have Core-Setup not strip them during source-build. `dotnet-runtime-...tar.gz` will be extracted and repacked as two RPMs: the bits and the debuginfo package.
* Make sure CoreCLR and CoreFX also don't strip native symbols during source-build. The native bits produced there are redistributed by Core-Setup with debug info included in the `so`, and go through the same RPM packaging process.
* Extract the Core-Setup managed symbols tar.gz and include its contents in the right dir in the debuginfo package.

Using `dotnet-symbol`, on the other hand, would make source-build more like the Microsoft build, and avoid a dependency on the symbol tar.gz in Core-Setup. `dotnet-symbol` could be used at packaging time: at the end of the build, use `dotnet-symbol` to gather up the debuginfo artifacts from the source-built symbol packages and put them in the debuginfo RPM. The plan this way:

* Get `dotnet-symbol` source-built.
* Use `dotnet-symbol` to search the `.symbols.nupkg` files for symbols for each runtime file that will be in the RPM, and put them in the right dir in the debuginfo package.
* For native symbols, we can choose to either have the repos not strip them, or use `dotnet-symbol`'s native symbol support to gather them up for the debuginfo package. Not stripping means more source-build-specific infra, but it does sound like it fits better into the typical RPM packaging flow.

I prefer the second because it unifies symbol flow in source-build with the Microsoft build. However, it requires some source-build work. The artifacts already exist for the first plan, so it seems to me like what will have to happen for now.

**Comment by omajid** [comment]
@dagood Am I correct in understand that either approach (with `dotnet-symbol` or without) will be transparent to the user? They just have to `dnf|apt install <package>` for things to work? Any changes will just be the responsibility of the individual building and packaging source-build?

If that's the case, then I am happy to use either approach.

> For native symbols, we can choose to either have the repos not strip them, or use dotnet-symbol's native symbol support to gather them up for the debuginfo package. Not stripping means more source-build-specific infra, but it does sound like it fits better into the typical RPM packaging flow.

I think we are already using the first approach on source-build side: https://github.com/dotnet/source-build/pull/272. At least we were with 2.x. And you are right, not stripping native debug info in the first place fits in better with the packaging workflow. The (native) debug packages are mostly auto-generated. Debian uses `dh_strip`, for example, which takes care of stripping the debug info and putting it in the right place on the file system and packaging it up: https://wiki.debian.org/AutomaticDebugPackages. If we were to strip the debug info, we would have to figure out how to do everything that the tooling already does.

**Comment by dagood** [comment]
> Am I correct in understand that either approach (with `dotnet-symbol` or without) will be transparent to the user? They just have to `dnf|apt install <package>` for things to work? Any changes will just be the responsibility of the individual building and packaging source-build?

That's right, for either of those plans I consider that the core goal.

> I think we are already using the first approach on source-build side

Yeah, the first approach is the status quo. We just have to make sure not stripping symbols keeps working and the symbol tar.gz keeps working, or anyone using source-build will have to adapt. This is overhead, but requires the least change from the dotnet repos. That's why I think it's what's going to happen. The second plan gets rid of the overhead by reducing source-build-specific native build configuration, but requires investigation to figure out all the new infra.

**Comment by omajid** [comment]
I looked at dll files vs pdb files in a 3.0 Preview 6 build (using source-build) and noticed that pdb files exist for all shared framwork dll files except:

    Microsoft.Win32.Registry.dll
    SOS.NETCore.dll
    System.IO.FileSystem.AccessControl.dll
    System.IO.Pipes.AccessControl.dll
    System.Private.CoreLib.dll
    System.Private.DataContractSerialization.dll
    System.Private.Uri.dll
    System.Private.Xml.dll
    System.Private.Xml.Linq.dll
    System.Runtime.WindowsRuntime.dll
    System.Runtime.WindowsRuntime.UI.Xaml.dll
    System.Security.AccessControl.dll
    System.Security.Cryptography.Cng.dll
    System.Security.Cryptography.OpenSsl.dll
    System.Security.Principal.Windows.dll

Is this expected?

My test script is available here: https://gist.github.com/omajid/bd283b8f284247512329a15ae59ce6fc

**Comment by dagood** [comment]
`SOS.NETCore.dll` is from CoreCLR, but isn't shipping in the runtime anymore with 3.0 (https://github.com/dotnet/coreclr/pull/25220) so I'm not concerned about that one.

The rest are CoreFX, and I wouldn't expect them missing--filed https://github.com/dotnet/core-setup/issues/7147.

**Comment by omajid** [comment]
I am closing this issue now, since the general work is all done. The only missing pdb is `System.Runtime.CompilerServices.Unsafe.dll` which is expected (see https://github.com/dotnet/runtime/issues/3679 for more details).
