### ISSUE TITLE
Analyze prebuilts for arcade

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#970]
The following prebuilt packages are included as dependencies in source-build by **arcade**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## Prebuilt Table Updated 2019-05-07

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Framework | 15.7.179 | 16.0.461 | Ref-Only
Microsoft.Build.Tasks.Core | 15.7.179 | 16.0.461 | Ref-Only
Microsoft.Build.Utilities.Core | 15.7.179 | 16.0.461 | Ref-Only
Microsoft.Build | 15.7.179 | 16.0.461 | Ref-Only
Microsoft.CodeAnalysis.CSharp | 2.9.0 | 3.1.0-beta2-19067-14 | Ref-Only
Microsoft.DotNet.PlatformAbstractions | 2.1.0 | 3.0.0-preview4-27615-11 | Ref-Only
NuGet.Versioning | 4.4.0 | 5.1.0-rtm.5921 | Ref-Only

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | -- 
Microsoft.Build.Tasks.Core | 15.7.179 | 16.0.0-preview.385 | 1. Change to use the source-built version - Requires https://github.com/dotnet/arcade/issues/393
Microsoft.Build | 15.7.179 | 16.0.0-preview.385 | 1. Change to use the source-built version - Requires https://github.com/dotnet/arcade/issues/393
Microsoft.CodeAnalysis.CSharp | 2.9.0 | 3.0.0-beta3-19067-14 | 1. Change to use the source-built version - Requires upgrading netstandard version, determine if that is ok
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 | | 2. Package is not critical to product and can be removed
Microsoft.DotNet.PlatformAbstractions | 2.1.0 | 3.0.0-preview-27324-5 | 1. Change to use source-built version
Microsoft.DotNet.SignTool | 1.0.0-beta.19073.5 | | 2. Package is not critical to product and can be removed
NuGet.Commands | 4.4.0 | 5.0.0-preview1.5754 | 1. Change to use source-built version
NuGet.Packaging | 4.4.0 | 5.0.0-preview1.5754 | 1. Change to use source-built version - Requires source change to src\Microsoft.DotNet.Build.Tasks.Packaging\src\GenerateNuSpec.cs because of api change
NuGet.ProjectModel | 4.4.0 | 5.0.0-preview1.5754 | 1. Change to use source-built version
NuGet.Versioning | 4.4.0 | 5.0.0-preview1.5754 | 1. Change to use source-built version
System.Collections.Immutable | 1.3.1 | | 3. The package is used as reference only
System.Net.Http | 4.3.3 | | 3. The package is used as reference only
System.Reflection.Metadata | 1.4.2 | | 3. The package is used as reference only
sn | 1.0.0 | | 2. Tool is not critical to product and can be removed
vswhere | 2.5.2 | | 2. Tool is not critical to product and can be removed

**Comment by markwilkie** [comment]
We need to update this issue with the plan to deal with these prebuilts by 3/1/2019.

cc/ @jcagme and @chcosta

**Comment by chcosta** [comment]
@dseefeld , I don't have access to the "SourceBuildPrebuiltReport"?  Can you help me get access?

What's the plan / mechanism to prevent new prebuilts from creeping in?

**Comment by crummel** [comment]
@chcosta dotnetsbchamps should have read access, but I added you explicitly to the access list, let us know if you still have problems.  We'd like to eventually have CI legs in each repo that build it in a source-build context and fail if new prebuilts are introduced.  Until then, we can turn on source-build treating any prebuilts as an error once they are eliminated, so we would catch it on the next update of the submodule in source-build.

**Comment by chcosta** [comment]
I've updated the plan.  @jcagme , @tmat , PTAL

**Comment by chcosta** [comment]
@jcagme is working on issue https://github.com/dotnet/arcade/issues/393, no ETA yet

**Comment by jcagme** [comment]
Tentative ETA couple of hours

**Comment by jcagme** [comment]
Testing changes but currently waiting on the lock thing...

**Comment by crummel** [comment]
I'm not sure I've heard about this issue, what do you mean by the lock thing?

**Comment by jcagme** [comment]
Oh, sorry, this is when the feed where we publish built packages is been used by other build locking it for write access so until that other build finishes other builds trying to write to it are just waiting https://dnceng.visualstudio.com/internal/_build/results?buildId=115919

**Comment by crummel** [comment]
Ah, okay.  Let me know if there's anything we can help with!

**Comment by jcagme** [comment]
Sadly there is not, there several efforts on making this better but for now we need to wait...

**Comment by jcagme** [comment]
FYI, I've just merged https://github.com/dotnet/arcade/pull/2183 and will babysit the official build just to make sure everything is ok.

**Comment by chcosta** [comment]
Status

PackageName                           | Status   | Category
------------------------------------- | -------- | -- 
Microsoft.Build.Tasks.Core            |          | 1. Change to use the source-built version - Requires https://github.com/dotnet/arcade/issues/393
Microsoft.Build                       |          | 1. Change to use the source-built version - Requires https://github.com/dotnet/arcade/issues/393
Microsoft.CodeAnalysis.CSharp         |          | 1. Change to use the source-built version - Requires upgrading netstandard version, determine if that is ok
Microsoft.DotNet.PlatformAbstractions |          | 1. Change to use source-built version
NuGet.Commands                        |          | 1. Change to use source-built version
NuGet.Packaging                       |          | 1. Change to use source-built version - Requires source change to src\Microsoft.DotNet.Build.Tasks.Packaging\src\GenerateNuSpec.cs because of api change
NuGet.ProjectModel                    |          | 1. Change to use source-built version
NuGet.Versioning                      |          | 1. Change to use source-built version
Microsoft.DiaSymReader.Pdb2Pdb        | Complete | 2. Package is not critical to product and can be removed
Microsoft.DotNet.SignTool             | Complete | 2. Package is not critical to product and can be removed
System.Collections.Immutable          | Complete | 3. The package is used as reference only
System.Net.Http                       | Complete | 3. The package is used as reference only
System.Reflection.Metadata            | Complete | 3. The package is used as reference only
sn                                    | Complete | 2. Tool is not critical to product and can be removed
vswhere                               | Complete | 2. Tool is not critical to product and can be removed

**Comment by chcosta** [comment]
Updated list in comment above.  All items are resolved.  Microsoft.CodeAnalysis.CSharp is going to change in the near future and that work is tracked in https://github.com/dotnet/arcade/issues/2748
