### ISSUE TITLE
Analyze prebuilts for toolset

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#973]
The following prebuilt packages are included as dependencies in source-build by **toolset**.  These need to be analyzed to determine how to avoid requiring packages that source-build doesn’t build.

1. Change to use the source-built version
1. Package is not critical to product and can be removed.  (i.e.test-specific, windows-specific, etc)
1. The package is used as reference only
1. The package should be built in source-build
1. Other – please elaborate on what you think should be done.

For more detailed usage information for these, please see the _Usage Exploration_ tab of the [SourceBuildPrebuiltReport](https://msit.powerbi.com/groups/dc6359c5-e96a-44ce-9d86-0af7fab1c15e/reports/64e989dd-8072-4d84-8268-140bde0cbc7d/ReportSectionc64da6d8334068f41e23).

## ~~Prebuilt Table Updated 2019-05-07~~

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Utilities.Core | 15.7.177 | 16.0.461 
Microsoft.Build | 15.7.177 | 16.0.461 
NuGet.Versioning | 4.3.0 | 5.1.0-rtm.5921 
System.Data.SqlClient | 4.3.0 |  

</br>

## Original Prebuilt Table

PackageName | PackageVersion | SourceBuiltVersion | Category
-- | -- | -- | --
Microsoft.Build.Utilities.Core | 15.7.177 | 16.0.0-preview.385 
Microsoft.Build | 15.7.177 | 16.0.0-preview.385 
Microsoft.DiaSymReader.Pdb2Pdb | 1.1.0-beta1-62506-02 |  
Microsoft.DotNet.PlatformAbstractions | 2.0.0 | 3.0.0-preview-27324-5 
Microsoft.DotNet.SignTool | 1.0.0-beta.19067.6 |  
Microsoft.SymbolUploader.Build.Task | 1.0.0-beta-63604-05 |  
NuGet.Versioning | 4.3.0 | 5.0.0-preview1.5754 
System.Reflection.Metadata | 1.4.2 |  
System.Runtime.InteropServices | 4.3.0 |  
XliffTasks | 0.2.0-beta-63004-01 | 0.2.0-beta-000048 
sn | 1.0.0 |  
vswhere | 2.5.2 |

**Comment by nguerrera** [comment]
### Category 4 (should be source-built version)
XliffTasks

### Category 3 (reference only - used in build tasks not in product)
Microsoft.Build.Utilities.Core
Microsoft.Build
System.Reflection.Metadata
NuGet.Versioning
Microsoft.DotNet.PlatformAbstractions

## Category 5 (needs investigation pulled in by publishing of fsc, probably gets conflict resolved away and is effectively reference only, but need to confirm)
System.Runtime.InteropServices

### Category 2 (not needed for source build and already fixed in arcade)
Microsoft.DiaSymReader.Pdb2Pdb
Microsoft.DotNet.SignTool
Microsoft.SymbolUploader.Build.Task
sn
vswhere

**Comment by nguerrera** [comment]
Filed this for category 5: https://github.com/dotnet/toolset/issues/440

**Comment by dseefeld** [comment]
All prebuilts removed.
